// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/extension_annotations/schema.json
// Generated by json_schema2dart

export 'schema_generated/extension_annotations_test.dart';
export 'schema_generated/validation_error.dart';
