import 'dart:convert';
import 'dart:io';

import 'package:schemamodeschema/src/generator.dart';
import 'package:test/test.dart';

void main() {
  final schemaPath = 'example/schemas/pubspec.subset.schema.json';

  late Map<String, dynamic> schema;
  late SchemaGenerator generator;

  setUpAll(() {
    final raw = File(schemaPath).readAsStringSync();
    schema = jsonDecode(raw) as Map<String, dynamic>;
    generator = SchemaGenerator(
      options: const SchemaGeneratorOptions(
        sourcePath: 'example/schemas/pubspec.subset.schema.json',
      ),
    );
  });

  test('builds IR mirroring existing MVP output', () {
    final ir = generator.buildIr(schema);

    expect(ir.rootClass.name, 'Pubspec');
    expect(
      ir.classes.map((c) => c.name),
      containsAll(<String>['Pubspec', 'PubspecEnvironment']),
    );

    final rootProperties = {
      for (final prop in ir.rootClass.properties) prop.fieldName: prop,
    };
    expect(
      rootProperties.keys,
      containsAll(<String>['name', 'version', 'environment', 'publishTo']),
    );
    expect(rootProperties['name']!.isRequired, isTrue);
    expect(rootProperties['environment']!.typeRef, isA<ObjectTypeRef>());

    expect(ir.enums, hasLength(1));
    final enumSpec = ir.enums.single;
    expect(enumSpec.name, 'PubspecPublishTo');
    expect(enumSpec.values.map((v) => v.identifier).toList(), [
      'none',
      'pubDev',
    ]);
  });

  test('emits Dart source unchanged from MVP', () {
    final generated = generator.generate(schema);

    const expected = '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pubspec.subset.schema.json
// Generated by json_schema2dart

/// A tiny subset of the pubspec.yaml structure to demonstrate generation.
class Pubspec {
  /// Package name.
  final String name;
  final String? version;
  final PubspecEnvironment? environment;
  /// Publish destination or 'none'.
  final PubspecPublishTo? publishTo;

  const Pubspec({
    required this.name,
    this.version,
    this.environment,
    this.publishTo,
  });

  factory Pubspec.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final name = json['name'] as String;
    remaining.remove('name');
    final version = json['version'] as String?;
    remaining.remove('version');
    final environment = json['environment'] == null ? null : PubspecEnvironment.fromJson((json['environment'] as Map).cast<String, dynamic>());
    remaining.remove('environment');
    final publishTo = json['publish_to'] == null ? null : PubspecPublishToJson.fromJson(json['publish_to'] as String);
    remaining.remove('publish_to');
    var unmatched = Map<String, dynamic>.from(remaining);
    return Pubspec(
      name: name,
      version: version,
      environment: environment,
      publishTo: publishTo,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    if (version != null) map['version'] = version;
    if (environment != null) map['environment'] = environment!.toJson();
    if (publishTo != null) map['publish_to'] = publishTo!.toJson();
    return map;
  }
}

class PubspecEnvironment {
  final String? sdk;
  final String? flutter;

  const PubspecEnvironment({
    this.sdk,
    this.flutter,
  });

  factory PubspecEnvironment.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final sdk = json['sdk'] as String?;
    remaining.remove('sdk');
    final flutter = json['flutter'] as String?;
    remaining.remove('flutter');
    var unmatched = Map<String, dynamic>.from(remaining);
    return PubspecEnvironment(
      sdk: sdk,
      flutter: flutter,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (sdk != null) map['sdk'] = sdk;
    if (flutter != null) map['flutter'] = flutter;
    return map;
  }
}

/// Publish destination or 'none'.
enum PubspecPublishTo { none, pubDev }

extension PubspecPublishToJson on PubspecPublishTo {
  String toJson() => const {
        PubspecPublishTo.none: 'none',
        PubspecPublishTo.pubDev: 'pub.dev',
      }[this]!;

  static PubspecPublishTo fromJson(String value) => const {
        'none': PubspecPublishTo.none,
        'pub.dev': PubspecPublishTo.pubDev,
      }[value]!;
}
''';

    expect(generated, expected);
  });

  test('plans multi-file output with barrel and per-type files', () {
    final ir = generator.buildIr(schema);
    final plan = generator.planMultiFile(ir, baseName: 'pubspec.subset');

    expect(plan.partsDirectory, 'pubspec_subset_generated');
    expect(plan.files.keys.toList(), [
      'pubspec.dart',
      'pubspec_environment.dart',
      'pubspec_publish_to.dart',
    ]);

    const expectedBarrel = '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pubspec.subset.schema.json
// Generated by json_schema2dart

export 'pubspec_subset_generated/pubspec.dart';
export 'pubspec_subset_generated/pubspec_environment.dart';
export 'pubspec_subset_generated/pubspec_publish_to.dart';
''';
    expect(plan.barrel, expectedBarrel);

    const expectedPubspec = '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pubspec.subset.schema.json
// Generated by json_schema2dart

import 'pubspec_environment.dart';
import 'pubspec_publish_to.dart';

/// A tiny subset of the pubspec.yaml structure to demonstrate generation.
class Pubspec {
  /// Package name.
  final String name;
  final String? version;
  final PubspecEnvironment? environment;
  /// Publish destination or 'none'.
  final PubspecPublishTo? publishTo;

  const Pubspec({
    required this.name,
    this.version,
    this.environment,
    this.publishTo,
  });

  factory Pubspec.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final name = json['name'] as String;
    remaining.remove('name');
    final version = json['version'] as String?;
    remaining.remove('version');
    final environment = json['environment'] == null ? null : PubspecEnvironment.fromJson((json['environment'] as Map).cast<String, dynamic>());
    remaining.remove('environment');
    final publishTo = json['publish_to'] == null ? null : PubspecPublishToJson.fromJson(json['publish_to'] as String);
    remaining.remove('publish_to');
    var unmatched = Map<String, dynamic>.from(remaining);
    return Pubspec(
      name: name,
      version: version,
      environment: environment,
      publishTo: publishTo,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    if (version != null) map['version'] = version;
    if (environment != null) map['environment'] = environment!.toJson();
    if (publishTo != null) map['publish_to'] = publishTo!.toJson();
    return map;
  }
}
''';
    expect(plan.files['pubspec.dart'], expectedPubspec);

    const expectedEnvironment = '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pubspec.subset.schema.json
// Generated by json_schema2dart

class PubspecEnvironment {
  final String? sdk;
  final String? flutter;

  const PubspecEnvironment({
    this.sdk,
    this.flutter,
  });

  factory PubspecEnvironment.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final sdk = json['sdk'] as String?;
    remaining.remove('sdk');
    final flutter = json['flutter'] as String?;
    remaining.remove('flutter');
    var unmatched = Map<String, dynamic>.from(remaining);
    return PubspecEnvironment(
      sdk: sdk,
      flutter: flutter,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (sdk != null) map['sdk'] = sdk;
    if (flutter != null) map['flutter'] = flutter;
    return map;
  }
}
''';
    expect(plan.files['pubspec_environment.dart'], expectedEnvironment);

    const expectedEnum = '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pubspec.subset.schema.json
// Generated by json_schema2dart

/// Publish destination or 'none'.
enum PubspecPublishTo { none, pubDev }

extension PubspecPublishToJson on PubspecPublishTo {
  String toJson() => const {
        PubspecPublishTo.none: 'none',
        PubspecPublishTo.pubDev: 'pub.dev',
      }[this]!;

  static PubspecPublishTo fromJson(String value) => const {
        'none': PubspecPublishTo.none,
        'pub.dev': PubspecPublishTo.pubDev,
      }[value]!;
}
''';
    expect(plan.files['pubspec_publish_to.dart'], expectedEnum);
  });
}
