// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/features/contains/schema.json
// Generated by json_schema2dart

class GroceryList {
  final List<dynamic>? items;

  const GroceryList({
    this.items,
  });

  factory GroceryList.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final items = json['items'] == null ? null : (json['items'] as List).map((e) => e).toList();
    remaining.remove('items');
    return GroceryList(
      items: items,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (items != null) map['items'] = items;
    return map;
  }
}
