targets:
  $default:
    builders:
      schema2model|schema_builder:
        generate_for:
          - lib/**.schema.json
          - lib/**.json
          - example/**.schema.json
          - example/**.json

builders:
  schema_builder:
    import: "package:schema2model/builder.dart"
    builder_factories: ["schemaToDartBuilder"]
    build_extensions:
      ".json": [".dart"]
    build_to: source
    auto_apply: root_package
