part of 'package:schema2model/src/generator.dart';

/// Configuration used by [SchemaGenerator].
class SchemaGeneratorOptions {
  const SchemaGeneratorOptions({
    this.rootClassName,
    this.inferredRootClass,
    this.preferCamelCase = true,
    this.emitDocumentation = true,
    this.header,
    this.sourcePath,
    this.singleFileOutput = false,
    this.baseUri,
    this.documentLoader,
    this.allowNetworkRefs = false,
    this.networkCachePath,
    this.onWarning,
    this.enableFormatHints = false,
    this.emitValidationHelpers = false,
    this.emitReadmeSnippets = false,
    this.defaultDialect = SchemaDialect.latest,
    this.supportedDialects = SchemaDialect.defaultDialectRegistry,
  });

  final String? rootClassName;
  final String? inferredRootClass;
  final bool preferCamelCase;
  final bool emitDocumentation;
  final String? header;
  final String? sourcePath;
  final bool singleFileOutput;
  final Uri? baseUri;
  final SchemaDocumentLoader? documentLoader;
  final bool allowNetworkRefs;
  final String? networkCachePath;
  final void Function(String message)? onWarning;
  final bool enableFormatHints;
  final bool emitValidationHelpers;
  final bool emitReadmeSnippets;
  final SchemaDialect? defaultDialect;
  final Map<String, SchemaDialect> supportedDialects;

  SchemaGeneratorOptions copyWith({
    String? inferredRootClass,
    String? sourcePath,
    bool? singleFileOutput,
    Uri? baseUri,
    SchemaDocumentLoader? documentLoader,
    bool? allowNetworkRefs,
    String? networkCachePath,
    void Function(String message)? onWarning,
    bool? enableFormatHints,
    bool? emitValidationHelpers,
    bool? emitReadmeSnippets,
    SchemaDialect? defaultDialect,
    Map<String, SchemaDialect>? supportedDialects,
  }) {
    return SchemaGeneratorOptions(
      rootClassName: rootClassName,
      inferredRootClass: inferredRootClass ?? this.inferredRootClass,
      preferCamelCase: preferCamelCase,
      emitDocumentation: emitDocumentation,
      header: header,
      sourcePath: sourcePath ?? this.sourcePath,
      singleFileOutput: singleFileOutput ?? this.singleFileOutput,
      baseUri: baseUri ?? this.baseUri,
      documentLoader: documentLoader ?? this.documentLoader,
      allowNetworkRefs: allowNetworkRefs ?? this.allowNetworkRefs,
      networkCachePath: networkCachePath ?? this.networkCachePath,
      onWarning: onWarning ?? this.onWarning,
      enableFormatHints: enableFormatHints ?? this.enableFormatHints,
      emitValidationHelpers:
          emitValidationHelpers ?? this.emitValidationHelpers,
      emitReadmeSnippets: emitReadmeSnippets ?? this.emitReadmeSnippets,
      defaultDialect: defaultDialect ?? this.defaultDialect,
      supportedDialects: supportedDialects ?? this.supportedDialects,
    );
  }

  String get effectiveHeader => header ?? 'Generated by json_schema2dart';

  String get effectiveRootClassName {
    final candidate = rootClassName ?? inferredRootClass ?? 'RootSchema';
    return _Naming.className(candidate);
  }
}
