part of 'package:schemamodeschema/src/generator.dart';

/// Configuration used by [SchemaGenerator].
class SchemaGeneratorOptions {
  const SchemaGeneratorOptions({
    this.rootClassName,
    this.inferredRootClass,
    this.preferCamelCase = true,
    this.emitDocumentation = true,
    this.header,
    this.sourcePath,
    this.singleFileOutput = false,
    this.baseUri,
    this.documentLoader,
    this.allowNetworkRefs = false,
    this.networkCachePath,
    this.onWarning,
  });

  final String? rootClassName;
  final String? inferredRootClass;
  final bool preferCamelCase;
  final bool emitDocumentation;
  final String? header;
  final String? sourcePath;
  final bool singleFileOutput;
  final Uri? baseUri;
  final SchemaDocumentLoader? documentLoader;
  final bool allowNetworkRefs;
  final String? networkCachePath;
  final void Function(String message)? onWarning;

  SchemaGeneratorOptions copyWith({
    String? inferredRootClass,
    String? sourcePath,
    bool? singleFileOutput,
    Uri? baseUri,
    SchemaDocumentLoader? documentLoader,
    bool? allowNetworkRefs,
    String? networkCachePath,
    void Function(String message)? onWarning,
  }) {
    return SchemaGeneratorOptions(
      rootClassName: rootClassName,
      inferredRootClass: inferredRootClass ?? this.inferredRootClass,
      preferCamelCase: preferCamelCase,
      emitDocumentation: emitDocumentation,
      header: header,
      sourcePath: sourcePath ?? this.sourcePath,
      singleFileOutput: singleFileOutput ?? this.singleFileOutput,
      baseUri: baseUri ?? this.baseUri,
      documentLoader: documentLoader ?? this.documentLoader,
      allowNetworkRefs: allowNetworkRefs ?? this.allowNetworkRefs,
      networkCachePath: networkCachePath ?? this.networkCachePath,
      onWarning: onWarning ?? this.onWarning,
    );
  }

  String get effectiveHeader => header ?? 'Generated by json_schema2dart';

  String get effectiveRootClassName {
    final candidate = rootClassName ?? inferredRootClass ?? 'RootSchema';
    return _Naming.className(candidate);
  }
}
