// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pubspec_subset/schema.json
// Generated by json_schema2dart

class PubspecEnvironment {
  final String? flutter;
  final String? sdk;

  const PubspecEnvironment({
    this.flutter,
    this.sdk,
  });

  factory PubspecEnvironment.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final flutter = json['flutter'] as String?;
    remaining.remove('flutter');
    final sdk = json['sdk'] as String?;
    remaining.remove('sdk');
    return PubspecEnvironment(
      flutter: flutter,
      sdk: sdk,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (flutter != null) map['flutter'] = flutter;
    if (sdk != null) map['sdk'] = sdk;
    return map;
  }
}
