// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pubspec_subset/schema.json
// Generated by json_schema2dart

/// Publish destination or 'none'.
enum PubspecPublishTo { none, pubDev }

extension PubspecPublishToJson on PubspecPublishTo {
  String toJson() => const {
        PubspecPublishTo.none: 'none',
        PubspecPublishTo.pubDev: 'pub.dev',
      }[this]!;

  static PubspecPublishTo fromJson(String value) => const {
        'none': PubspecPublishTo.none,
        'pub.dev': PubspecPublishTo.pubDev,
      }[value]!;
}
