// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'github_action_branding_color.dart';
import 'github_action_branding_icon.dart';

/// You can use a color and Feather icon to create a badge to personalize and distinguish your action. Badges are shown next to your action name in GitHub Marketplace.
class GithubActionBranding {
  /// The background color of the badge.
  final GithubActionBrandingColor? color;

  /// The name of the Feather icon to use.
  final GithubActionBrandingIcon? icon;

  const GithubActionBranding({this.color, this.icon});

  factory GithubActionBranding.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final color = json['color'] == null
        ? null
        : GithubActionBrandingColorJson.fromJson(json['color'] as String);
    remaining.remove('color');
    final icon = json['icon'] == null
        ? null
        : GithubActionBrandingIconJson.fromJson(json['icon'] as String);
    remaining.remove('icon');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      throw ArgumentError(
        'Unexpected additional properties: ${unmatched.keys.join(', ')}',
      );
    }
    return GithubActionBranding(color: color, icon: icon);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (color != null) map['color'] = color!.toJson();
    if (icon != null) map['icon'] = icon!.toJson();
    return map;
  }
}
