// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

/// The background color of the badge.
enum GithubActionBrandingColor {
  white,
  black,
  yellow,
  blue,
  green,
  orange,
  red,
  purple,
  grayDark,
}

extension GithubActionBrandingColorJson on GithubActionBrandingColor {
  String toJson() => const {
    GithubActionBrandingColor.white: 'white',
    GithubActionBrandingColor.black: 'black',
    GithubActionBrandingColor.yellow: 'yellow',
    GithubActionBrandingColor.blue: 'blue',
    GithubActionBrandingColor.green: 'green',
    GithubActionBrandingColor.orange: 'orange',
    GithubActionBrandingColor.red: 'red',
    GithubActionBrandingColor.purple: 'purple',
    GithubActionBrandingColor.grayDark: 'gray-dark',
  }[this]!;

  static GithubActionBrandingColor fromJson(String value) => const {
    'white': GithubActionBrandingColor.white,
    'black': GithubActionBrandingColor.black,
    'yellow': GithubActionBrandingColor.yellow,
    'blue': GithubActionBrandingColor.blue,
    'green': GithubActionBrandingColor.green,
    'orange': GithubActionBrandingColor.orange,
    'red': GithubActionBrandingColor.red,
    'purple': GithubActionBrandingColor.purple,
    'gray-dark': GithubActionBrandingColor.grayDark,
  }[value]!;
}
