// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'runs_composite_steps_item.dart';
import 'runs_javascript_using.dart';

part 'runs_javascript.dart';
part 'runs_composite.dart';
part 'runs_docker.dart';

sealed class GithubActionRuns {
  const GithubActionRuns();

  factory GithubActionRuns.fromJson(Map<String, dynamic> json) {
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    final constMatches = <GithubActionRuns Function(Map<String, dynamic>)>[];
    final constMatchNames = <String>[];
    if (json['using'] == 'composite') {
      constMatches.add(RunsComposite.fromJson);
      constMatchNames.add('RunsComposite');
    }
    if (json['using'] == 'docker') {
      constMatches.add(RunsDocker.fromJson);
      constMatchNames.add('RunsDocker');
    }
    if (constMatches.length == 1) {
      return constMatches.single(json);
    }
    if (constMatches.length > 1) {
      throw ArgumentError(
        'Ambiguous GithubActionRuns variant matched const heuristics: ${constMatchNames.join(', ')}',
      );
    }
    final requiredMatches = <GithubActionRuns Function(Map<String, dynamic>)>[];
    final requiredMatchNames = <String>[];
    if (keys.contains('using') && keys.contains('main')) {
      requiredMatches.add(RunsJavascript.fromJson);
      requiredMatchNames.add('RunsJavascript');
    }
    if (keys.contains('using') && keys.contains('steps')) {
      requiredMatches.add(RunsComposite.fromJson);
      requiredMatchNames.add('RunsComposite');
    }
    if (keys.contains('using') && keys.contains('image')) {
      requiredMatches.add(RunsDocker.fromJson);
      requiredMatchNames.add('RunsDocker');
    }
    if (requiredMatches.length == 1) {
      return requiredMatches.single(json);
    }
    if (requiredMatches.length > 1) {
      throw ArgumentError(
        'Ambiguous GithubActionRuns variant matched required-property heuristics: ${requiredMatchNames.join(', ')}',
      );
    }
    throw ArgumentError(
      'No GithubActionRuns variant matched heuristics (keys: ${sortedKeys.join(', ')}).',
    );
  }

  Map<String, dynamic> toJson();
}
