// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

/// A string identifier to associate with the output. The value of `<output_id>` is a map of the output's metadata. The `<output_id>` must be a unique identifier within the outputs object. The `<output_id>` must start with a letter or `_` and contain only alphanumeric characters, `-`, or `_`.
class OutputsCompositePatternProperty1 {
  /// A string description of the output parameter.
  final String description;

  /// The value that the output parameter will be mapped to. You can set this to a string or an expression with context. For example, you can use the steps context to set the value of an output to the output value of a step.
  final String value;

  const OutputsCompositePatternProperty1({
    required this.description,
    required this.value,
  });

  factory OutputsCompositePatternProperty1.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final description = json['description'] as String;
    remaining.remove('description');
    final value = json['value'] as String;
    remaining.remove('value');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      throw ArgumentError(
        'Unexpected additional properties: ${unmatched.keys.join(', ')}',
      );
    }
    return OutputsCompositePatternProperty1(
      description: description,
      value: value,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['description'] = description;
    map['value'] = value;
    return map;
  }
}
