// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

part of 'github_action_runs.dart';

/// Configures the path to the action's code and the application used to execute the code.
class RunsJavascript extends GithubActionRuns {
  /// The file that contains your action code. The application specified in `using` executes this file.
  final String main;

  /// Allows you to run a script at the end of a job, once the `main:` action has completed. For example, you can use `post:` to terminate certain processes or remove unneeded files. The application specified with the `using` syntax will execute this file. The `post:` action always runs by default but you can override this using `post-if`.
  final String? post;
  final String? postIf;

  /// Allows you to run a script at the start of a job, before the `main:` action begins. For example, you can use `pre:` to run a prerequisite setup script. The application specified with the `using` syntax will execute this file. The `pre:` action always runs by default but you can override this using `pre-if`.
  final String? pre;
  final String? preIf;

  /// The application used to execute the code specified in `main`.
  final RunsJavascriptUsing using;

  const RunsJavascript({
    required this.main,
    this.post,
    this.postIf,
    this.pre,
    this.preIf,
    required this.using,
  }) : super();

  factory RunsJavascript.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final main = json['main'] as String;
    remaining.remove('main');
    final post = json['post'] as String?;
    remaining.remove('post');
    final postIf = json['post-if'] as String?;
    remaining.remove('post-if');
    final pre = json['pre'] as String?;
    remaining.remove('pre');
    final preIf = json['pre-if'] as String?;
    remaining.remove('pre-if');
    final using = RunsJavascriptUsingJson.fromJson(json['using'] as String);
    remaining.remove('using');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      throw ArgumentError(
        'Unexpected additional properties: ${unmatched.keys.join(', ')}',
      );
    }
    return RunsJavascript(
      main: main,
      post: post,
      postIf: postIf,
      pre: pre,
      preIf: preIf,
      using: using,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['main'] = main;
    if (post != null) map['post'] = post;
    if (postIf != null) map['post-if'] = postIf;
    if (pre != null) map['pre'] = pre;
    if (preIf != null) map['pre-if'] = preIf;
    map['using'] = using.toJson();
    return map;
  }
}
