// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

/// The application used to execute the code specified in `main`.
enum RunsJavascriptUsing { node12, node16, node20, node24 }

extension RunsJavascriptUsingJson on RunsJavascriptUsing {
  String toJson() => const {
    RunsJavascriptUsing.node12: 'node12',
    RunsJavascriptUsing.node16: 'node16',
    RunsJavascriptUsing.node20: 'node20',
    RunsJavascriptUsing.node24: 'node24',
  }[this]!;

  static RunsJavascriptUsing fromJson(String value) => const {
    'node12': RunsJavascriptUsing.node12,
    'node16': RunsJavascriptUsing.node16,
    'node20': RunsJavascriptUsing.node20,
    'node24': RunsJavascriptUsing.node24,
  }[value]!;
}
