// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

/// A map of the input parameters defined by the action. Each input parameter is a key/value pair. Input parameters are set as environment variables. The variable is prefixed with INPUT_ and converted to upper case.
class RunsCompositeStepsItemWith {
  const RunsCompositeStepsItemWith();

  factory RunsCompositeStepsItemWith.fromJson(Map<String, dynamic> json) {
    return RunsCompositeStepsItemWith();
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    return map;
  }
}
