// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

part of 'github_action_runs.dart';

/// Configures the path to the composite action, and the application used to execute the code.
class RunsComposite extends GithubActionRuns {
  /// The run steps that you plan to run in this action.
  final List<RunsCompositeStepsItem> steps;

  /// To use a composite run steps action, set this to 'composite'.
  final String using;

  const RunsComposite({required this.steps, required this.using}) : super();

  factory RunsComposite.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final steps = (json['steps'] as List)
        .map(
          (e) => RunsCompositeStepsItem.fromJson(
            (e as Map).cast<String, dynamic>(),
          ),
        )
        .toList();
    remaining.remove('steps');
    final using = json['using'] as String;
    remaining.remove('using');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      throw ArgumentError(
        'Unexpected additional properties: ${unmatched.keys.join(', ')}',
      );
    }
    return RunsComposite(steps: steps, using: using);
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['steps'] = steps.map((e) => e.toJson()).toList();
    map['using'] = using;
    return map;
  }
}
