// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

part of 'github_action_runs.dart';

/// Configures the image used for the Docker action.
class RunsDocker extends GithubActionRuns {
  /// An array of strings that define the inputs for a Docker container. Inputs can include hardcoded strings. GitHub passes the `args` to the container's `ENTRYPOINT` when the container starts up.
  /// The `args` are used in place of the `CMD` instruction in a `Dockerfile`. If you use `CMD` in your `Dockerfile`, use the guidelines ordered by preference:
  /// - Document required arguments in the action's README and omit them from the `CMD` instruction.
  /// - Use defaults that allow using the action without specifying any `args`.
  /// - If the action exposes a `--help` flag, or something similar, use that to make your action self-documenting.
  final List<String>? args;

  /// Overrides the Docker `ENTRYPOINT` in the `Dockerfile`, or sets it if one wasn't already specified. Use `entrypoint` when the `Dockerfile` does not specify an `ENTRYPOINT` or you want to override the `ENTRYPOINT` instruction. If you omit `entrypoint`, the commands you specify in the Docker `ENTRYPOINT` instruction will execute. The Docker `ENTRYPOINT instruction has a *shell* form and *exec* form. The Docker `ENTRYPOINT` documentation recommends using the *exec* form of the `ENTRYPOINT` instruction.
  final String? entrypoint;

  /// Specifies a key/value map of environment variables to set in the container environment.
  final dynamic env;

  /// The Docker image to use as the container to run the action. The value can be the Docker base image name, a local `Dockerfile` in your repository, or a public image in Docker Hub or another registry. To reference a `Dockerfile` local to your repository, use a path relative to your action metadata file. The `docker` application will execute this file.
  final String image;

  /// Allows you to run a cleanup script once the `runs.entrypoint` action has completed. GitHub Actions uses `docker run` to launch this action. Because GitHub Actions runs the script inside a new container using the same base image, the runtime state is different from the main `entrypoint` container. You can access any state you need in either the workspace, `HOME`, or as a `STATE_` variable. The `post-entrypoint:` action always runs by default but you can override this using `post-if`.
  final String? postEntrypoint;
  final String? postIf;

  /// Allows you to run a script before the `entrypoint` action begins. For example, you can use `pre-entrypoint:` to run a prerequisite setup script. GitHub Actions uses `docker run` to launch this action, and runs the script inside a new container that uses the same base image. This means that the runtime state is different from the main `entrypoint` container, and any states you require must be accessed in either the workspace, `HOME`, or as a `STATE_` variable. The `pre-entrypoint:` action always runs by default but you can override this using `pre-if`.
  final String? preEntrypoint;
  final String? preIf;

  /// You must set this value to 'docker'.
  final String using;

  const RunsDocker({
    this.args,
    this.entrypoint,
    this.env,
    required this.image,
    this.postEntrypoint,
    this.postIf,
    this.preEntrypoint,
    this.preIf,
    required this.using,
  }) : super();

  factory RunsDocker.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final args = json['args'] == null
        ? null
        : (json['args'] as List).map((e) => e as String).toList();
    remaining.remove('args');
    final entrypoint = json['entrypoint'] as String?;
    remaining.remove('entrypoint');
    final env = json['env'];
    remaining.remove('env');
    final image = json['image'] as String;
    remaining.remove('image');
    final postEntrypoint = json['post-entrypoint'] as String?;
    remaining.remove('post-entrypoint');
    final postIf = json['post-if'] as String?;
    remaining.remove('post-if');
    final preEntrypoint = json['pre-entrypoint'] as String?;
    remaining.remove('pre-entrypoint');
    final preIf = json['pre-if'] as String?;
    remaining.remove('pre-if');
    final using = json['using'] as String;
    remaining.remove('using');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      throw ArgumentError(
        'Unexpected additional properties: ${unmatched.keys.join(', ')}',
      );
    }
    return RunsDocker(
      args: args,
      entrypoint: entrypoint,
      env: env,
      image: image,
      postEntrypoint: postEntrypoint,
      postIf: postIf,
      preEntrypoint: preEntrypoint,
      preIf: preIf,
      using: using,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (args != null) map['args'] = args;
    if (entrypoint != null) map['entrypoint'] = entrypoint;
    if (env != null) map['env'] = env;
    map['image'] = image;
    if (postEntrypoint != null) map['post-entrypoint'] = postEntrypoint;
    if (postIf != null) map['post-if'] = postIf;
    if (preEntrypoint != null) map['pre-entrypoint'] = preEntrypoint;
    if (preIf != null) map['pre-if'] = preIf;
    map['using'] = using;
    return map;
  }
}
