// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

export 'schema_generated/root_schema.dart';
export 'schema_generated/class0.dart';
export 'schema_generated/runs_composite_steps_item_with.dart';
export 'schema_generated/runs_composite_steps_item.dart';
export 'schema_generated/class02.dart';
export 'schema_generated/outputs_pattern_property1.dart';
export 'schema_generated/outputs.dart';
export 'schema_generated/outputs_composite_pattern_property1.dart';
export 'schema_generated/outputs_composite.dart';
export 'schema_generated/root_schema_branding.dart';
export 'schema_generated/root_schema_inputs_pattern_property1.dart';
export 'schema_generated/root_schema_inputs.dart';
export 'schema_generated/root_schema_runs.dart';
export 'schema_generated/runs_javascript_using.dart';
export 'schema_generated/class1.dart';
export 'schema_generated/root_schema_branding_color.dart';
export 'schema_generated/root_schema_branding_icon.dart';
