// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/extension_annotations/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// x-category: testing
/// x-version: 1.0.0
class ExtensionAnnotationsTest {
  /// x-displayName: Age
  /// x-validationMessage: Must be 18 or older
  final int? age;
  /// The user's name
  /// x-displayName: User Name
  /// x-helpText: Enter your full name
  /// x-placeholder: John Doe
  final String userName;

  const ExtensionAnnotationsTest({
    this.age,
    required this.userName,
  });

  factory ExtensionAnnotationsTest.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final age = json['age'] as int?;
    remaining.remove('age');
    final userName = json['userName'] as String;
    remaining.remove('userName');
    return ExtensionAnnotationsTest(
      age: age,
      userName: userName,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (age != null) map['age'] = age;
    map['userName'] = userName;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'age');
    final _value0 = age;
    if (_value0 != null) {
      context?.markProperty(pointer, 'age');
      if (_value0 < 18) {
        throwValidationError(_ptr0, 'minimum', 'Expected value >= 18 but found ' + _value0.toString() + '.');
      }
    }
    final _ptr1 = appendJsonPointer(pointer, 'userName');
    final _value1 = userName;
    context?.markProperty(pointer, 'userName');
  }
}
