// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/unevaluated_properties/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class Settings {
  final String? known;
  final Map<String, String>? unevaluatedProperties;

  const Settings({
    this.known,
    this.unevaluatedProperties,
  });

  factory Settings.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final known = json['known'] as String?;
    remaining.remove('known');
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, String>? unevaluatedPropertiesValue;
    if (unmatched.isNotEmpty) {
      final unevaluatedPropertiesMap = <String, String>{};
      for (final entry in unmatched.entries) {
        final value = entry.value;
        unevaluatedPropertiesMap[entry.key] = value as String;
      }
      unevaluatedPropertiesValue = unevaluatedPropertiesMap.isEmpty ? null : unevaluatedPropertiesMap;
      unmatched = <String, dynamic>{};
    } else {
      unevaluatedPropertiesValue = null;
    }
    return Settings(
      known: known,
      unevaluatedProperties: unevaluatedPropertiesValue,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (known != null) map['known'] = known;
    if (unevaluatedProperties != null) {
      unevaluatedProperties!.forEach((key, value) {
        map[key] = value;
      });
    }
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
