// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/contains/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class GroceryList {
  final List<String>? items;

  const GroceryList({
    this.items,
  });

  factory GroceryList.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final items = json['items'] == null ? null : (json['items'] as List).map((e) => e as String).toList();
    remaining.remove('items');
    return GroceryList(
      items: items,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (items != null) map['items'] = items;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'items');
    final _value0 = items;
    if (_value0 != null) {
      context?.markProperty(pointer, 'items');
      final _lenp0 = _value0.length;
      final _evaluatedp0 = List<bool>.filled(_lenp0, false);
      for (var i = 0; i < _lenp0; i++) {
        final itemPointer = appendJsonPointer(_ptr0, i.toString());
        final item = _value0[i];
      }
      var _containsCountp0 = 0;
      for (var i = 0; i < _lenp0; i++) {
        final itemPointer = appendJsonPointer(_ptr0, i.toString());
        final item = _value0[i];
        final matches = item is String;
        if (matches) {
          _containsCountp0++;
          if (!_evaluatedp0[i]) { _evaluatedp0[i] = true; }
          context?.markItem(_ptr0, i);
        }
      }
      if (_containsCountp0 < 2) {
        throwValidationError(_ptr0, 'contains', 'Expected at least 2 item(s) matching "contains" but found ' + _containsCountp0.toString() + '.');
      }
      if (_containsCountp0 > 3) {
        throwValidationError(_ptr0, 'contains', 'Expected at most 3 item(s) matching "contains" but found ' + _containsCountp0.toString() + '.');
      }
    }
  }
}
