// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pubspec.subset.schema.json
// Generated by json_schema2dart

class PubspecEnvironment {
  final String? sdk;
  final String? flutter;

  const PubspecEnvironment({
    this.sdk,
    this.flutter,
  });

  factory PubspecEnvironment.fromJson(Map<String, dynamic> json) {
    return PubspecEnvironment(
      sdk: json['sdk'] as String?,
      flutter: json['flutter'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (sdk != null) map['sdk'] = sdk;
    if (flutter != null) map['flutter'] = flutter;
    return map;
  }
}
