// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pubspec.subset.schema.json
// Generated by json_schema2dart

/// Publish destination or 'none'.
enum PubspecPublishTo { none, pub_dev }

extension PubspecPublishToJson on PubspecPublishTo {
  String toJson() => const {
        PubspecPublishTo.none: 'none',
        PubspecPublishTo.pub_dev: 'pub.dev',
      }[this]!;

  static PubspecPublishTo fromJson(String value) => const {
        'none': PubspecPublishTo.none,
        'pub.dev': PubspecPublishTo.pub_dev,
      }[value]!;
}
