// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pubspec.subset.schema.json
// Generated by json_schema2dart

import 'pubspec_environment.dart';
import 'pubspec_publish_to.dart';

/// A tiny subset of the pubspec.yaml structure to demonstrate generation.
class Pubspec {
  /// Package name.
  final String name;
  final String? version;
  final PubspecEnvironment? environment;
  /// Publish destination or 'none'.
  final PubspecPublishTo? publishTo;

  const Pubspec({
    required this.name,
    this.version,
    this.environment,
    this.publishTo,
  });

  factory Pubspec.fromJson(Map<String, dynamic> json) {
    return Pubspec(
      name: json['name'] as String,
      version: json['version'] as String?,
      environment: json['environment'] == null ? null : PubspecEnvironment.fromJson((json['environment'] as Map).cast<String, dynamic>()),
      publishTo: json['publish_to'] == null ? null : PubspecPublishToJson.fromJson(json['publish_to'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    if (version != null) map['version'] = version;
    if (environment != null) map['environment'] = environment!.toJson();
    if (publishTo != null) map['publish_to'] = publishTo!.toJson();
    return map;
  }
}
