// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/anchor_test/schema.json
// Generated by json_schema2dart

export 'schema_generated/person.dart';
export 'schema_generated/validation_error.dart';
