// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

export 'schema_generated/github_workflow.dart';
export 'schema_generated/class1_item.dart';
export 'schema_generated/container_credentials.dart';
export 'schema_generated/class0.dart';
export 'schema_generated/container.dart';
export 'schema_generated/defaults_run.dart';
export 'schema_generated/defaults.dart';
export 'schema_generated/permissions_event.dart';
export 'schema_generated/environment.dart';
export 'schema_generated/class02.dart';
export 'schema_generated/step.dart';
export 'schema_generated/concurrency.dart';
export 'schema_generated/class03.dart';
export 'schema_generated/reusable_workflow_call_job_strategy.dart';
export 'schema_generated/normal_job_outputs.dart';
export 'schema_generated/class2.dart';
export 'schema_generated/normal_job_services.dart';
export 'schema_generated/normal_job_strategy.dart';
export 'schema_generated/workflow_dispatch_input.dart';
export 'schema_generated/github_workflow_jobs_pattern_property1.dart';
export 'schema_generated/github_workflow_jobs.dart';
export 'schema_generated/class3.dart';
export 'schema_generated/class12.dart';
export 'schema_generated/class13.dart';
export 'schema_generated/class22_schedule_item.dart';
export 'schema_generated/class22_workflow_call_inputs_pattern_property1.dart';
export 'schema_generated/class22_workflow_call_inputs.dart';
export 'schema_generated/class22_workflow_call_outputs_pattern_property1.dart';
export 'schema_generated/class22_workflow_call_outputs.dart';
export 'schema_generated/class22_workflow_call.dart';
export 'schema_generated/class22_workflow_dispatch_inputs.dart';
export 'schema_generated/class22_workflow_dispatch.dart';
export 'schema_generated/class22.dart';
export 'schema_generated/class1.dart';
export 'schema_generated/architecture.dart';
export 'schema_generated/permissions_event_actions.dart';
export 'schema_generated/permissions_event_models.dart';
export 'schema_generated/event.dart';
export 'schema_generated/machine.dart';
export 'schema_generated/workflow_dispatch_input_type.dart';
export 'schema_generated/class22_workflow_call_inputs_pattern_property1_type.dart';
export 'schema_generated/validation_error.dart';
