// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/pubspec_subset/schema.json
// Generated by json_schema2dart

import 'pubspec_environment.dart';
import 'pubspec_publish_to.dart';

/// A tiny subset of the pubspec.yaml structure to demonstrate generation.
class Pubspec {
  final PubspecEnvironment? environment;
  /// Package name.
  final String name;
  /// Publish destination or 'none'.
  final PubspecPublishTo? publishTo;
  final String? version;

  const Pubspec({
    this.environment,
    required this.name,
    this.publishTo,
    this.version,
  });

  factory Pubspec.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final environment = json['environment'] == null ? null : PubspecEnvironment.fromJson((json['environment'] as Map).cast<String, dynamic>());
    remaining.remove('environment');
    final name = json['name'] as String;
    remaining.remove('name');
    final publishTo = json['publish_to'] == null ? null : PubspecPublishToJson.fromJson(json['publish_to'] as String);
    remaining.remove('publish_to');
    final version = json['version'] as String?;
    remaining.remove('version');
    return Pubspec(
      environment: environment,
      name: name,
      publishTo: publishTo,
      version: version,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (environment != null) map['environment'] = environment!.toJson();
    map['name'] = name;
    if (publishTo != null) map['publish_to'] = publishTo!.toJson();
    if (version != null) map['version'] = version;
    return map;
  }
}
