// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/unevaluated_properties/schema.json
// Generated by json_schema2dart

class Settings {
  final String? known;

  const Settings({
    this.known,
  });

  factory Settings.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final known = json['known'] as String?;
    remaining.remove('known');
    return Settings(
      known: known,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (known != null) map['known'] = known;
    return map;
  }
}
