// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/sample_project/lib/schemas/todo_list.json
// Generated by json_schema2dart

import 'todo_list_metadata_reminder_dependency_channel.dart';
import 'validation_error.dart';

class TodoListMetadataReminderDependency {
  final TodoListMetadataReminderDependencyChannel? channel;

  const TodoListMetadataReminderDependency({
    this.channel,
  });

  factory TodoListMetadataReminderDependency.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final channel = json['channel'] == null ? null : TodoListMetadataReminderDependencyChannelJson.fromJson(json['channel'] as String);
    remaining.remove('channel');
    return TodoListMetadataReminderDependency(
      channel: channel,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (channel != null) map['channel'] = channel!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
