// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/sample_project/lib/schemas/todo_list.json
// Generated by json_schema2dart

import 'todo_list_metadata_reminder.dart';
import 'todo_list_metadata_reminder_dependency.dart';
import 'validation_error.dart';

class TodoListMetadata {
  final String? color;
  final String owner;
  final TodoListMetadataReminder? reminder;

  const TodoListMetadata({
    this.color,
    required this.owner,
    this.reminder,
  });

  factory TodoListMetadata.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final color = json['color'] as String?;
    remaining.remove('color');
    final owner = json['owner'] as String;
    remaining.remove('owner');
    final reminder = json['reminder'] == null ? null : TodoListMetadataReminder.fromJson((json['reminder'] as Map).cast<String, dynamic>());
    remaining.remove('reminder');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected unevaluated properties: $unexpected');
    }
    return TodoListMetadata(
      color: color,
      owner: owner,
      reminder: reminder,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (color != null) map['color'] = color;
    map['owner'] = owner;
    if (reminder != null) map['reminder'] = reminder!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'color');
    final _value0 = color;
    if (_value0 != null) {
      context?.markProperty(pointer, 'color');
      final _patternp0 = RegExp('^#[0-9A-Fa-f]{6}\$');
      if (!_patternp0.hasMatch(_value0)) {
        throwValidationError(_ptr0, 'pattern', 'Expected value to match pattern ^#[0-9A-Fa-f]{6}\$ but found ' + _value0 + '.');
      }
    }
    final _ptr1 = appendJsonPointer(pointer, 'owner');
    final _value1 = owner;
    context?.markProperty(pointer, 'owner');
    final _ptr2 = appendJsonPointer(pointer, 'reminder');
    final _value2 = reminder;
    if (_value2 != null) {
      context?.markProperty(pointer, 'reminder');
      _value2.validate(pointer: _ptr2, context: context);
    }
    if (_value2 != null) {
      final _dependent2 = TodoListMetadataReminderDependency.fromJson((_value2!).toJson());
      _dependent2.validate(pointer: _ptr2, context: context);
    }
  }
}
