// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/sample_project/lib/schemas/todo_list.json
// Generated by json_schema2dart

import 'todo_list_item.dart';
import 'todo_list_metadata.dart';
import 'validation_error.dart';

class TodoList {
  /// Collection of to-do entries.
  final List<TodoListItem> items;
  final TodoListMetadata? metadata;
  /// Display name for this list.
  final String name;
  /// Optional labels applied to the list.
  final List<String>? tags;

  const TodoList({
    required this.items,
    this.metadata,
    required this.name,
    this.tags,
  });

  factory TodoList.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final items = (json['items'] as List).map((e) => TodoListItem.fromJson((e as Map).cast<String, dynamic>())).toList();
    remaining.remove('items');
    final metadata = json['metadata'] == null ? null : TodoListMetadata.fromJson((json['metadata'] as Map).cast<String, dynamic>());
    remaining.remove('metadata');
    final name = json['name'] as String;
    remaining.remove('name');
    final tags = json['tags'] == null ? null : (json['tags'] as List).map((e) => e as String).toList();
    remaining.remove('tags');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return TodoList(
      items: items,
      metadata: metadata,
      name: name,
      tags: tags,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['items'] = items.map((e) => e.toJson()).toList();
    if (metadata != null) map['metadata'] = metadata!.toJson();
    map['name'] = name;
    if (tags != null) map['tags'] = tags;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'items');
    final _value0 = items;
    context?.markProperty(pointer, 'items');
    final _ptr1 = appendJsonPointer(pointer, 'metadata');
    final _value1 = metadata;
    if (_value1 != null) {
      context?.markProperty(pointer, 'metadata');
      _value1.validate(pointer: _ptr1, context: context);
    }
    final _ptr2 = appendJsonPointer(pointer, 'name');
    final _value2 = name;
    context?.markProperty(pointer, 'name');
    final _ptr3 = appendJsonPointer(pointer, 'tags');
    final _value3 = tags;
    if (_value3 != null) {
      context?.markProperty(pointer, 'tags');
      final _lenp3 = _value3.length;
      final _evaluatedp3 = List<bool>.filled(_lenp3, false);
      for (var i = 0; i < _lenp3; i++) {
        final itemPointer = appendJsonPointer(_ptr3, i.toString());
        final item = _value3[i];
        _evaluatedp3[i] = true;
        context?.markItem(_ptr3, i);
      }
      var _containsCountp3 = 0;
      for (var i = 0; i < _lenp3; i++) {
        final itemPointer = appendJsonPointer(_ptr3, i.toString());
        final item = _value3[i];
        final matches = item is String;
        if (matches) {
          _containsCountp3++;
          if (!_evaluatedp3[i]) { _evaluatedp3[i] = true; }
          context?.markItem(_ptr3, i);
        }
      }
      if (_containsCountp3 < 1) {
        throwValidationError(_ptr3, 'contains', 'Expected at least 1 item(s) matching "contains" but found ' + _containsCountp3.toString() + '.');
      }
      if (_containsCountp3 > 5) {
        throwValidationError(_ptr3, 'contains', 'Expected at most 5 item(s) matching "contains" but found ' + _containsCountp3.toString() + '.');
      }
    }
  }
}
