// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/sample_project/lib/schemas/todo_list.json
// Generated by json_schema2dart

import 'validation_error.dart';

class TodoListItem {
  /// Default: false.
  final bool? done;
  final String title;

  const TodoListItem({
    this.done = false,
    required this.title,
  });

  factory TodoListItem.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final done = (json['done'] as bool?) ?? false;
    remaining.remove('done');
    final title = json['title'] as String;
    remaining.remove('title');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional and unevaluated properties: $unexpected');
    }
    return TodoListItem(
      done: done,
      title: title,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (done != null) map['done'] = done;
    map['title'] = title;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
