// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/sample_project/lib/schemas/todo_list.json
// Generated by json_schema2dart

enum TodoListMetadataReminderDependencyChannel { email, sms, push }

extension TodoListMetadataReminderDependencyChannelJson on TodoListMetadataReminderDependencyChannel {
  String toJson() => const {
        TodoListMetadataReminderDependencyChannel.email: 'email',
        TodoListMetadataReminderDependencyChannel.sms: 'sms',
        TodoListMetadataReminderDependencyChannel.push: 'push',
      }[this]!;

  static TodoListMetadataReminderDependencyChannel fromJson(String value) => const {
        'email': TodoListMetadataReminderDependencyChannel.email,
        'sms': TodoListMetadataReminderDependencyChannel.sms,
        'push': TodoListMetadataReminderDependencyChannel.push,
      }[value]!;
}
