// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/sample_project/lib/schemas/todo_list.json
// Generated by json_schema2dart

import 'validation_error.dart';

class TodoListMetadataReminder {
  final String? channel;
  /// Format: date-time (format hints disabled).
  /// 
  /// Date and time as defined by RFC 3339 date-time.
  /// 
  /// See https://json-schema.org/draft/2020-12/json-schema-validation.html#name-dates-times-and-duration.
  final String time;
  final String? timezone;

  const TodoListMetadataReminder({
    this.channel,
    required this.time,
    this.timezone,
  });

  factory TodoListMetadataReminder.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final channel = json['channel'] as String?;
    remaining.remove('channel');
    final time = json['time'] as String;
    remaining.remove('time');
    final timezone = json['timezone'] as String?;
    remaining.remove('timezone');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected unevaluated properties: $unexpected');
    }
    return TodoListMetadataReminder(
      channel: channel,
      time: time,
      timezone: timezone,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (channel != null) map['channel'] = channel;
    map['time'] = time;
    if (timezone != null) map['timezone'] = timezone;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'channel');
    final _value0 = channel;
    if (_value0 != null) {
      context?.markProperty(pointer, 'channel');
    }
    final _ptr1 = appendJsonPointer(pointer, 'time');
    final _value1 = time;
    context?.markProperty(pointer, 'time');
    final _ptr2 = appendJsonPointer(pointer, 'timezone');
    final _value2 = timezone;
    if (_value2 != null) {
      context?.markProperty(pointer, 'timezone');
    }
    if (_value0 != null) {
      if (_value2 == null) {
        throwValidationError(pointer, 'dependentRequired', 'Property "timezone" must be present when "channel" is defined.');
      }
    }
  }
}
