// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/features/contains/schema.json
// Generated by json_schema2dart

export 'schema_generated/grocery_list.dart';
export 'schema_generated/validation_error.dart';
