// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum Architecture { arm32, x64, x86 }

extension ArchitectureJson on Architecture {
  String toJson() => const {
        Architecture.arm32: 'ARM32',
        Architecture.x64: 'x64',
        Architecture.x86: 'x86',
      }[this]!;

  static Architecture fromJson(String value) => const {
        'ARM32': Architecture.arm32,
        'x64': Architecture.x64,
        'x86': Architecture.x86,
      }[value]!;
}
