// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

/// Required if input is defined for the on.workflow_call keyword. The value of this parameter is a string specifying the data type of the input. This must be one of: boolean, number, or string.
enum Class22WorkflowCallInputsPatternProperty1Type { boolean, number, string }

extension Class22WorkflowCallInputsPatternProperty1TypeJson on Class22WorkflowCallInputsPatternProperty1Type {
  String toJson() => const {
        Class22WorkflowCallInputsPatternProperty1Type.boolean: 'boolean',
        Class22WorkflowCallInputsPatternProperty1Type.number: 'number',
        Class22WorkflowCallInputsPatternProperty1Type.string: 'string',
      }[this]!;

  static Class22WorkflowCallInputsPatternProperty1Type fromJson(String value) => const {
        'boolean': Class22WorkflowCallInputsPatternProperty1Type.boolean,
        'number': Class22WorkflowCallInputsPatternProperty1Type.number,
        'string': Class22WorkflowCallInputsPatternProperty1Type.string,
      }[value]!;
}
