// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum Class12 { inherit }

extension Class12Json on Class12 {
  String toJson() => const {
        Class12.inherit: 'inherit',
      }[this]!;

  static Class12 fromJson(String value) => const {
        'inherit': Class12.inherit,
      }[value]!;
}
