// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

class Class1Item {
  final Map<String, dynamic>? additionalProperties;

  const Class1Item({
    this.additionalProperties,
  });

  factory Class1Item.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, dynamic>? additionalPropertiesValue;
    if (unmatched.isNotEmpty) {
      final additionalPropertiesMap = <String, dynamic>{};
      for (final entry in unmatched.entries) {
        final value = entry.value;
        additionalPropertiesMap[entry.key] = value;
      }
      additionalPropertiesValue = additionalPropertiesMap.isEmpty ? null : additionalPropertiesMap;
      unmatched = <String, dynamic>{};
    } else {
      additionalPropertiesValue = null;
    }
    return Class1Item(
      additionalProperties: additionalPropertiesValue,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (additionalProperties != null) {
      additionalProperties!.forEach((key, value) {
        map[key] = value;
      });
    }
    return map;
  }
}
