// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'class22_workflow_call_inputs.dart';
import 'class22_workflow_call_outputs.dart';
import 'validation_error.dart';

/// Allows workflows to be reused by other workflows.
class Class22WorkflowCall {
  /// When using the workflow_call keyword, you can optionally specify inputs that are passed to the called workflow from the caller workflow.
  final Class22WorkflowCallInputs? inputs;
  /// When using the workflow_call keyword, you can optionally specify inputs that are passed to the called workflow from the caller workflow.
  final Class22WorkflowCallOutputs? outputs;
  /// A map of the secrets that can be used in the called workflow. Within the called workflow, you can use the secrets context to refer to a secret.
  final dynamic secrets;

  const Class22WorkflowCall({
    this.inputs,
    this.outputs,
    this.secrets,
  });

  factory Class22WorkflowCall.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final inputs = json['inputs'] == null ? null : Class22WorkflowCallInputs.fromJson((json['inputs'] as Map).cast<String, dynamic>());
    remaining.remove('inputs');
    final outputs = json['outputs'] == null ? null : Class22WorkflowCallOutputs.fromJson((json['outputs'] as Map).cast<String, dynamic>());
    remaining.remove('outputs');
    final secrets = json['secrets'];
    remaining.remove('secrets');
    return Class22WorkflowCall(
      inputs: inputs,
      outputs: outputs,
      secrets: secrets,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (inputs != null) map['inputs'] = inputs!.toJson();
    if (outputs != null) map['outputs'] = outputs!.toJson();
    if (secrets != null) map['secrets'] = secrets;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
