// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'class22_workflow_call_outputs_pattern_property1.dart';

/// When using the workflow_call keyword, you can optionally specify inputs that are passed to the called workflow from the caller workflow.
class Class22WorkflowCallOutputs {
  final Map<String, Class22WorkflowCallOutputsPatternProperty1>? patternProperties;

  const Class22WorkflowCallOutputs({
    this.patternProperties,
  });

  factory Class22WorkflowCallOutputs.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, Class22WorkflowCallOutputsPatternProperty1>? patternPropertiesValue;
    {
      final patternPropertiesMap = <String, Class22WorkflowCallOutputsPatternProperty1>{};
      final unmatchedAfterPattern = <String, dynamic>{};
      for (final entry in unmatched.entries) {
        final key = entry.key;
        final value = entry.value;
        var matched = false;
        if (!matched && RegExp('^[_a-zA-Z][a-zA-Z0-9_-]*\$').hasMatch(key)) {
          patternPropertiesMap[key] = Class22WorkflowCallOutputsPatternProperty1.fromJson((value as Map).cast<String, dynamic>());
          matched = true;
        }
        if (!matched) {
          unmatchedAfterPattern[key] = value;
        }
      }
      patternPropertiesValue = patternPropertiesMap.isEmpty ? null : patternPropertiesMap;
      unmatched = unmatchedAfterPattern;
    }
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return Class22WorkflowCallOutputs(
      patternProperties: patternPropertiesValue,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (patternProperties != null) {
      for (final entry in patternProperties!.entries) {
        final key = entry.key;
        final value = entry.value;
        var matched = false;
        if (!matched && RegExp('^[_a-zA-Z][a-zA-Z0-9_-]*\$').hasMatch(key)) {
          map[key] = value.toJson();
          matched = true;
        }
        if (!matched) {
          map[key] = value;
        }
      }
    }
    return map;
  }
}
