// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum Class0 { readAll, writeAll }

extension Class0Json on Class0 {
  String toJson() => const {
        Class0.readAll: 'read-all',
        Class0.writeAll: 'write-all',
      }[this]!;

  static Class0 fromJson(String value) => const {
        'read-all': Class0.readAll,
        'write-all': Class0.writeAll,
      }[value]!;
}
