// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class Class03 {
  final Map<String, dynamic>? patternProperties;
  final Map<String, dynamic>? additionalProperties;

  const Class03({
    this.patternProperties,
    this.additionalProperties,
  });

  factory Class03.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, dynamic>? patternPropertiesValue;
    {
      final patternPropertiesMap = <String, dynamic>{};
      final unmatchedAfterPattern = <String, dynamic>{};
      for (final entry in unmatched.entries) {
        final key = entry.key;
        final value = entry.value;
        var matched = false;
        if (!matched && RegExp('^(in|ex)clude\$').hasMatch(key)) {
          patternPropertiesMap[key] = value;
          matched = true;
        }
        if (!matched) {
          unmatchedAfterPattern[key] = value;
        }
      }
      patternPropertiesValue = patternPropertiesMap.isEmpty ? null : patternPropertiesMap;
      unmatched = unmatchedAfterPattern;
    }
    Map<String, dynamic>? additionalPropertiesValue;
    if (unmatched.isNotEmpty) {
      final additionalPropertiesMap = <String, dynamic>{};
      for (final entry in unmatched.entries) {
        final value = entry.value;
        additionalPropertiesMap[entry.key] = value;
      }
      additionalPropertiesValue = additionalPropertiesMap.isEmpty ? null : additionalPropertiesMap;
      unmatched = <String, dynamic>{};
    } else {
      additionalPropertiesValue = null;
    }
    return Class03(
      patternProperties: patternPropertiesValue,
      additionalProperties: additionalPropertiesValue,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (patternProperties != null) {
      for (final entry in patternProperties!.entries) {
        final key = entry.key;
        final value = entry.value;
        var matched = false;
        if (!matched && RegExp('^(in|ex)clude\$').hasMatch(key)) {
          map[key] = value;
          matched = true;
        }
        if (!matched) {
          map[key] = value;
        }
      }
    }
    if (additionalProperties != null) {
      additionalProperties!.forEach((key, value) {
        map[key] = value;
      });
    }
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
