// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum Class1 { bash, pwsh, python, sh, cmd, powershell }

extension Class1Json on Class1 {
  String toJson() => const {
        Class1.bash: 'bash',
        Class1.pwsh: 'pwsh',
        Class1.python: 'python',
        Class1.sh: 'sh',
        Class1.cmd: 'cmd',
        Class1.powershell: 'powershell',
      }[this]!;

  static Class1 fromJson(String value) => const {
        'bash': Class1.bash,
        'pwsh': Class1.pwsh,
        'python': Class1.python,
        'sh': Class1.sh,
        'cmd': Class1.cmd,
        'powershell': Class1.powershell,
      }[value]!;
}
