// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'class22_workflow_call_inputs_pattern_property1_type.dart';

/// A string identifier to associate with the input. The value of <input_id> is a map of the input's metadata. The <input_id> must be a unique identifier within the inputs object. The <input_id> must start with a letter or _ and contain only alphanumeric characters, -, or _.
class Class22WorkflowCallInputsPatternProperty1 {
  /// The default value is used when an input parameter isn't specified in a workflow file.
  final bool? default_;
  /// A string description of the input parameter.
  final String? description;
  /// A boolean to indicate whether the action requires the input parameter. Set to true when the parameter is required.
  final bool? required;
  /// Required if input is defined for the on.workflow_call keyword. The value of this parameter is a string specifying the data type of the input. This must be one of: boolean, number, or string.
  final Class22WorkflowCallInputsPatternProperty1Type type;

  const Class22WorkflowCallInputsPatternProperty1({
    this.default_,
    this.description,
    this.required,
    required this.type,
  });

  factory Class22WorkflowCallInputsPatternProperty1.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final default_ = json['default'] as bool?;
    remaining.remove('default');
    final description = json['description'] as String?;
    remaining.remove('description');
    final required = json['required'] as bool?;
    remaining.remove('required');
    final type = Class22WorkflowCallInputsPatternProperty1TypeJson.fromJson(json['type'] as String);
    remaining.remove('type');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return Class22WorkflowCallInputsPatternProperty1(
      default_: default_,
      description: description,
      required: required,
      type: type,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (default_ != null) map['default'] = default_;
    if (description != null) map['description'] = description;
    if (required != null) map['required'] = required;
    map['type'] = type.toJson();
    return map;
  }
}
