// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'class22_schedule_item.dart';
import 'class22_workflow_call.dart';
import 'class22_workflow_dispatch.dart';
import 'validation_error.dart';

class Class22 {
  /// Runs your workflow anytime the branch_protection_rule event occurs. More than one activity type triggers this event.
  final dynamic branchProtectionRule;
  /// Runs your workflow anytime the check_run event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/checks/runs.
  final dynamic checkRun;
  /// Runs your workflow anytime the check_suite event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/checks/suites/.
  final dynamic checkSuite;
  /// Runs your workflow anytime someone creates a branch or tag, which triggers the create event. For information about the REST API, see https://developer.github.com/v3/git/refs/#create-a-reference.
  final dynamic create;
  /// Runs your workflow anytime someone deletes a branch or tag, which triggers the delete event. For information about the REST API, see https://developer.github.com/v3/git/refs/#delete-a-reference.
  final dynamic delete;
  /// Runs your workflow anytime someone creates a deployment, which triggers the deployment event. Deployments created with a commit SHA may not have a Git ref. For information about the REST API, see https://developer.github.com/v3/repos/deployments/.
  final dynamic deployment;
  /// Runs your workflow anytime a third party provides a deployment status, which triggers the deployment_status event. Deployments created with a commit SHA may not have a Git ref. For information about the REST API, see https://developer.github.com/v3/repos/deployments/#create-a-deployment-status.
  final dynamic deploymentStatus;
  /// Runs your workflow anytime the discussion event occurs. More than one activity type triggers this event. For information about the GraphQL API, see https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions
  final dynamic discussion;
  /// Runs your workflow anytime the discussion_comment event occurs. More than one activity type triggers this event. For information about the GraphQL API, see https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions
  final dynamic discussionComment;
  /// Runs your workflow anytime when someone forks a repository, which triggers the fork event. For information about the REST API, see https://developer.github.com/v3/repos/forks/#create-a-fork.
  final dynamic fork;
  /// Runs your workflow when someone creates or updates a Wiki page, which triggers the gollum event.
  final dynamic gollum;
  /// Runs your workflow anytime the issue_comment event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/issues/comments/.
  final dynamic issueComment;
  /// Runs your workflow anytime the issues event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/issues.
  final dynamic issues;
  /// Runs your workflow anytime the label event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/issues/labels/.
  final dynamic label;
  /// Runs your workflow when a pull request is added to a merge queue, which adds the pull request to a merge group. For information about the merge queue, see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue .
  final dynamic mergeGroup;
  /// Runs your workflow anytime the milestone event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/issues/milestones/.
  final dynamic milestone;
  /// Runs your workflow anytime someone pushes to a GitHub Pages-enabled branch, which triggers the page_build event. For information about the REST API, see https://developer.github.com/v3/repos/pages/.
  final dynamic pageBuild;
  /// Runs your workflow anytime the project event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/projects/.
  final dynamic project;
  /// Runs your workflow anytime the project_card event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/projects/cards.
  final dynamic projectCard;
  /// Runs your workflow anytime the project_column event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/projects/columns.
  final dynamic projectColumn;
  /// Runs your workflow anytime someone makes a private repository public, which triggers the public event. For information about the REST API, see https://developer.github.com/v3/repos/#edit.
  final dynamic public;
  /// Runs your workflow anytime the pull_request event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/pulls.
  /// Note: Workflows do not run on private base repositories when you open a pull request from a forked repository.
  /// When you create a pull request from a forked repository to the base repository, GitHub sends the pull_request event to the base repository and no pull request events occur on the forked repository.
  /// Workflows don't run on forked repositories by default. You must enable GitHub Actions in the Actions tab of the forked repository.
  /// The permissions for the GITHUB_TOKEN in forked repositories is read-only. For more information about the GITHUB_TOKEN, see https://help.github.com/en/articles/virtual-environments-for-github-actions.
  final dynamic pullRequest;
  /// Runs your workflow anytime the pull_request_review event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/pulls/reviews.
  /// Note: Workflows do not run on private base repositories when you open a pull request from a forked repository.
  /// When you create a pull request from a forked repository to the base repository, GitHub sends the pull_request event to the base repository and no pull request events occur on the forked repository.
  /// Workflows don't run on forked repositories by default. You must enable GitHub Actions in the Actions tab of the forked repository.
  /// The permissions for the GITHUB_TOKEN in forked repositories is read-only. For more information about the GITHUB_TOKEN, see https://help.github.com/en/articles/virtual-environments-for-github-actions.
  final dynamic pullRequestReview;
  /// Runs your workflow anytime a comment on a pull request's unified diff is modified, which triggers the pull_request_review_comment event. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/pulls/comments.
  /// Note: Workflows do not run on private base repositories when you open a pull request from a forked repository.
  /// When you create a pull request from a forked repository to the base repository, GitHub sends the pull_request event to the base repository and no pull request events occur on the forked repository.
  /// Workflows don't run on forked repositories by default. You must enable GitHub Actions in the Actions tab of the forked repository.
  /// The permissions for the GITHUB_TOKEN in forked repositories is read-only. For more information about the GITHUB_TOKEN, see https://help.github.com/en/articles/virtual-environments-for-github-actions.
  final dynamic pullRequestReviewComment;
  /// This event is similar to pull_request, except that it runs in the context of the base repository of the pull request, rather than in the merge commit. This means that you can more safely make your secrets available to the workflows triggered by the pull request, because only workflows defined in the commit on the base repository are run. For example, this event allows you to create workflows that label and comment on pull requests, based on the contents of the event payload.
  final dynamic pullRequestTarget;
  /// Runs your workflow when someone pushes to a repository branch, which triggers the push event.
  /// Note: The webhook payload available to GitHub Actions does not include the added, removed, and modified attributes in the commit object. You can retrieve the full commit object using the REST API. For more information, see https://developer.github.com/v3/repos/commits/#get-a-single-commit.
  final dynamic push;
  /// Runs your workflow anytime a package is published or updated. For more information, see https://help.github.com/en/github/managing-packages-with-github-packages.
  final dynamic registryPackage;
  /// Runs your workflow anytime the release event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/repos/releases/ in the GitHub Developer documentation.
  final dynamic release;
  /// You can use the GitHub API to trigger a webhook event called repository_dispatch when you want to trigger a workflow for activity that happens outside of GitHub. For more information, see https://developer.github.com/v3/repos/#create-a-repository-dispatch-event.
  /// To trigger the custom repository_dispatch webhook event, you must send a POST request to a GitHub API endpoint and provide an event_type name to describe the activity type. To trigger a workflow run, you must also configure your workflow to use the repository_dispatch event.
  final dynamic repositoryDispatch;
  /// You can schedule a workflow to run at specific UTC times using POSIX cron syntax (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07). Scheduled workflows run on the latest commit on the default or base branch. The shortest interval you can run scheduled workflows is once every 5 minutes.
  /// Note: GitHub Actions does not support the non-standard syntax @yearly, @monthly, @weekly, @daily, @hourly, and @reboot.
  /// You can use crontab guru (https://crontab.guru/). to help generate your cron syntax and confirm what time it will run. To help you get started, there is also a list of crontab guru examples (https://crontab.guru/examples.html).
  final List<Class22ScheduleItem>? schedule;
  /// Runs your workflow anytime the status of a Git commit changes, which triggers the status event. For information about the REST API, see https://developer.github.com/v3/repos/statuses/.
  final dynamic status;
  /// Runs your workflow anytime the watch event occurs. More than one activity type triggers this event. For information about the REST API, see https://developer.github.com/v3/activity/starring/.
  final dynamic watch;
  /// Allows workflows to be reused by other workflows.
  final Class22WorkflowCall? workflowCall;
  /// You can now create workflows that are manually triggered with the new workflow_dispatch event. You will then see a 'Run workflow' button on the Actions tab, enabling you to easily trigger a run.
  final Class22WorkflowDispatch? workflowDispatch;
  /// This event occurs when a workflow run is requested or completed, and allows you to execute a workflow based on the finished result of another workflow. For example, if your pull_request workflow generates build artifacts, you can create a new workflow that uses workflow_run to analyze the results and add a comment to the original pull request.
  final dynamic workflowRun;

  const Class22({
    this.branchProtectionRule,
    this.checkRun,
    this.checkSuite,
    this.create,
    this.delete,
    this.deployment,
    this.deploymentStatus,
    this.discussion,
    this.discussionComment,
    this.fork,
    this.gollum,
    this.issueComment,
    this.issues,
    this.label,
    this.mergeGroup,
    this.milestone,
    this.pageBuild,
    this.project,
    this.projectCard,
    this.projectColumn,
    this.public,
    this.pullRequest,
    this.pullRequestReview,
    this.pullRequestReviewComment,
    this.pullRequestTarget,
    this.push,
    this.registryPackage,
    this.release,
    this.repositoryDispatch,
    this.schedule,
    this.status,
    this.watch,
    this.workflowCall,
    this.workflowDispatch,
    this.workflowRun,
  });

  factory Class22.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final branchProtectionRule = json['branch_protection_rule'];
    remaining.remove('branch_protection_rule');
    final checkRun = json['check_run'];
    remaining.remove('check_run');
    final checkSuite = json['check_suite'];
    remaining.remove('check_suite');
    final create = json['create'];
    remaining.remove('create');
    final delete = json['delete'];
    remaining.remove('delete');
    final deployment = json['deployment'];
    remaining.remove('deployment');
    final deploymentStatus = json['deployment_status'];
    remaining.remove('deployment_status');
    final discussion = json['discussion'];
    remaining.remove('discussion');
    final discussionComment = json['discussion_comment'];
    remaining.remove('discussion_comment');
    final fork = json['fork'];
    remaining.remove('fork');
    final gollum = json['gollum'];
    remaining.remove('gollum');
    final issueComment = json['issue_comment'];
    remaining.remove('issue_comment');
    final issues = json['issues'];
    remaining.remove('issues');
    final label = json['label'];
    remaining.remove('label');
    final mergeGroup = json['merge_group'];
    remaining.remove('merge_group');
    final milestone = json['milestone'];
    remaining.remove('milestone');
    final pageBuild = json['page_build'];
    remaining.remove('page_build');
    final project = json['project'];
    remaining.remove('project');
    final projectCard = json['project_card'];
    remaining.remove('project_card');
    final projectColumn = json['project_column'];
    remaining.remove('project_column');
    final public = json['public'];
    remaining.remove('public');
    final pullRequest = json['pull_request'];
    remaining.remove('pull_request');
    final pullRequestReview = json['pull_request_review'];
    remaining.remove('pull_request_review');
    final pullRequestReviewComment = json['pull_request_review_comment'];
    remaining.remove('pull_request_review_comment');
    final pullRequestTarget = json['pull_request_target'];
    remaining.remove('pull_request_target');
    final push = json['push'];
    remaining.remove('push');
    final registryPackage = json['registry_package'];
    remaining.remove('registry_package');
    final release = json['release'];
    remaining.remove('release');
    final repositoryDispatch = json['repository_dispatch'];
    remaining.remove('repository_dispatch');
    final schedule = json['schedule'] == null ? null : (json['schedule'] as List).map((e) => Class22ScheduleItem.fromJson((e as Map).cast<String, dynamic>())).toList();
    remaining.remove('schedule');
    final status = json['status'];
    remaining.remove('status');
    final watch = json['watch'];
    remaining.remove('watch');
    final workflowCall = json['workflow_call'] == null ? null : Class22WorkflowCall.fromJson((json['workflow_call'] as Map).cast<String, dynamic>());
    remaining.remove('workflow_call');
    final workflowDispatch = json['workflow_dispatch'] == null ? null : Class22WorkflowDispatch.fromJson((json['workflow_dispatch'] as Map).cast<String, dynamic>());
    remaining.remove('workflow_dispatch');
    final workflowRun = json['workflow_run'];
    remaining.remove('workflow_run');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return Class22(
      branchProtectionRule: branchProtectionRule,
      checkRun: checkRun,
      checkSuite: checkSuite,
      create: create,
      delete: delete,
      deployment: deployment,
      deploymentStatus: deploymentStatus,
      discussion: discussion,
      discussionComment: discussionComment,
      fork: fork,
      gollum: gollum,
      issueComment: issueComment,
      issues: issues,
      label: label,
      mergeGroup: mergeGroup,
      milestone: milestone,
      pageBuild: pageBuild,
      project: project,
      projectCard: projectCard,
      projectColumn: projectColumn,
      public: public,
      pullRequest: pullRequest,
      pullRequestReview: pullRequestReview,
      pullRequestReviewComment: pullRequestReviewComment,
      pullRequestTarget: pullRequestTarget,
      push: push,
      registryPackage: registryPackage,
      release: release,
      repositoryDispatch: repositoryDispatch,
      schedule: schedule,
      status: status,
      watch: watch,
      workflowCall: workflowCall,
      workflowDispatch: workflowDispatch,
      workflowRun: workflowRun,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (branchProtectionRule != null) map['branch_protection_rule'] = branchProtectionRule;
    if (checkRun != null) map['check_run'] = checkRun;
    if (checkSuite != null) map['check_suite'] = checkSuite;
    if (create != null) map['create'] = create;
    if (delete != null) map['delete'] = delete;
    if (deployment != null) map['deployment'] = deployment;
    if (deploymentStatus != null) map['deployment_status'] = deploymentStatus;
    if (discussion != null) map['discussion'] = discussion;
    if (discussionComment != null) map['discussion_comment'] = discussionComment;
    if (fork != null) map['fork'] = fork;
    if (gollum != null) map['gollum'] = gollum;
    if (issueComment != null) map['issue_comment'] = issueComment;
    if (issues != null) map['issues'] = issues;
    if (label != null) map['label'] = label;
    if (mergeGroup != null) map['merge_group'] = mergeGroup;
    if (milestone != null) map['milestone'] = milestone;
    if (pageBuild != null) map['page_build'] = pageBuild;
    if (project != null) map['project'] = project;
    if (projectCard != null) map['project_card'] = projectCard;
    if (projectColumn != null) map['project_column'] = projectColumn;
    if (public != null) map['public'] = public;
    if (pullRequest != null) map['pull_request'] = pullRequest;
    if (pullRequestReview != null) map['pull_request_review'] = pullRequestReview;
    if (pullRequestReviewComment != null) map['pull_request_review_comment'] = pullRequestReviewComment;
    if (pullRequestTarget != null) map['pull_request_target'] = pullRequestTarget;
    if (push != null) map['push'] = push;
    if (registryPackage != null) map['registry_package'] = registryPackage;
    if (release != null) map['release'] = release;
    if (repositoryDispatch != null) map['repository_dispatch'] = repositoryDispatch;
    if (schedule != null) map['schedule'] = schedule!.map((e) => e.toJson()).toList();
    if (status != null) map['status'] = status;
    if (watch != null) map['watch'] = watch;
    if (workflowCall != null) map['workflow_call'] = workflowCall!.toJson();
    if (workflowDispatch != null) map['workflow_dispatch'] = workflowDispatch!.toJson();
    if (workflowRun != null) map['workflow_run'] = workflowRun;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
