// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

class Concurrency {
  /// To cancel any currently running job or workflow in the same concurrency group, specify cancel-in-progress: true.
  final dynamic cancelInProgress;
  /// When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled.
  final String group;

  const Concurrency({
    this.cancelInProgress,
    required this.group,
  });

  factory Concurrency.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final cancelInProgress = json['cancel-in-progress'];
    remaining.remove('cancel-in-progress');
    final group = json['group'] as String;
    remaining.remove('group');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return Concurrency(
      cancelInProgress: cancelInProgress,
      group: group,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (cancelInProgress != null) map['cancel-in-progress'] = cancelInProgress;
    map['group'] = group;
    return map;
  }
}
