// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'container_credentials.dart';

class Container {
  /// If the image's container registry requires authentication to pull the image, you can use credentials to set a map of the username and password. The credentials are the same values that you would provide to the `docker login` command.
  final ContainerCredentials? credentials;
  /// Sets an array of environment variables in the container.
  final dynamic env;
  /// The Docker image to use as the container to run the action. The value can be the Docker Hub image name or a registry name.
  final String image;
  /// Additional Docker container resource options. For a list of options, see https://docs.docker.com/engine/reference/commandline/create/#options.
  final String? options;
  /// Sets an array of ports to expose on the container.
  final List<dynamic>? ports;
  /// Sets an array of volumes for the container to use. You can use volumes to share data between services or other steps in a job. You can specify named Docker volumes, anonymous Docker volumes, or bind mounts on the host.
  /// To specify a volume, you specify the source and destination path: <source>:<destinationPath>
  /// The <source> is a volume name or an absolute path on the host machine, and <destinationPath> is an absolute path in the container.
  final List<String>? volumes;

  const Container({
    this.credentials,
    this.env,
    required this.image,
    this.options,
    this.ports,
    this.volumes,
  });

  factory Container.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final credentials = json['credentials'] == null ? null : ContainerCredentials.fromJson((json['credentials'] as Map).cast<String, dynamic>());
    remaining.remove('credentials');
    final env = json['env'];
    remaining.remove('env');
    final image = json['image'] as String;
    remaining.remove('image');
    final options = json['options'] as String?;
    remaining.remove('options');
    final ports = json['ports'] == null ? null : (json['ports'] as List).map((e) => e).toList();
    remaining.remove('ports');
    final volumes = json['volumes'] == null ? null : (json['volumes'] as List).map((e) => e as String).toList();
    remaining.remove('volumes');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return Container(
      credentials: credentials,
      env: env,
      image: image,
      options: options,
      ports: ports,
      volumes: volumes,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (credentials != null) map['credentials'] = credentials!.toJson();
    if (env != null) map['env'] = env;
    map['image'] = image;
    if (options != null) map['options'] = options;
    if (ports != null) map['ports'] = ports;
    if (volumes != null) map['volumes'] = volumes;
    return map;
  }
}
