// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'defaults_run.dart';
import 'validation_error.dart';

class Defaults {
  final DefaultsRun? run;

  const Defaults({
    this.run,
  });

  factory Defaults.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final run = json['run'] == null ? null : DefaultsRun.fromJson((json['run'] as Map).cast<String, dynamic>());
    remaining.remove('run');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return Defaults(
      run: run,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (run != null) map['run'] = run!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
