// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// The environment that the job references
class Environment {
  /// The name of the environment configured in the repo.
  final String name;
  /// A deployment URL
  final String? url;

  const Environment({
    required this.name,
    this.url,
  });

  factory Environment.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final name = json['name'] as String;
    remaining.remove('name');
    final url = json['url'] as String?;
    remaining.remove('url');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return Environment(
      name: name,
      url: url,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = name;
    if (url != null) map['url'] = url;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
