// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'defaults.dart';
import 'normal_job_outputs.dart';
import 'normal_job_services.dart';
import 'normal_job_strategy.dart';
import 'reusable_workflow_call_job_strategy.dart';
import 'step.dart';
import 'validation_error.dart';

part 'normal_job.dart';
part 'reusable_workflow_call_job.dart';

sealed class GithubWorkflowJobsPatternProperty1 {
  const GithubWorkflowJobsPatternProperty1();

  void validate({String pointer = '', ValidationContext? context});

  factory GithubWorkflowJobsPatternProperty1.fromJson(Map<String, dynamic> json) {
    final keys = json.keys.toSet();
    final sortedKeys = keys.toList()..sort();
    final requiredMatches = <GithubWorkflowJobsPatternProperty1 Function(Map<String, dynamic>)>[];
    final requiredMatchNames = <String>[];
    if (keys.contains('runs-on')) {
      requiredMatches.add(NormalJob.fromJson);
      requiredMatchNames.add('NormalJob');
    }
    if (keys.contains('uses')) {
      requiredMatches.add(ReusableWorkflowCallJob.fromJson);
      requiredMatchNames.add('ReusableWorkflowCallJob');
    }
    if (requiredMatches.length == 1) {
      return requiredMatches.single(json);
    }
    if (requiredMatches.length > 1) {
      throw ArgumentError('Ambiguous GithubWorkflowJobsPatternProperty1 variant matched required-property heuristics: ${requiredMatchNames.join(', ')}');
    }
    throw ArgumentError('No GithubWorkflowJobsPatternProperty1 variant matched heuristics (keys: ${sortedKeys.join(', ')}).');
  }

  Map<String, dynamic> toJson();
}
