// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

part of 'github_workflow_jobs_pattern_property1.dart';

/// Each job must have an id to associate with the job. The key job_id is a string and its value is a map of the job's configuration data. You must replace <job_id> with a string that is unique to the jobs object. The <job_id> must start with a letter or _ and contain only alphanumeric characters, -, or _.
class NormalJob extends GithubWorkflowJobsPatternProperty1 {
  /// Concurrency ensures that only a single job or workflow using the same concurrency group will run at a time. A concurrency group can be any string or expression. The expression can use any context except for the secrets context.
  /// You can also specify concurrency at the workflow level.
  /// When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled. To also cancel any currently running job or workflow in the same concurrency group, specify cancel-in-progress: true.
  final dynamic concurrency;
  /// A container to run any steps in a job that don't already specify a container. If you have steps that use both script and container actions, the container actions will run as sibling containers on the same network with the same volume mounts.
  /// If you do not set a container, all steps will run directly on the host specified by runs-on unless a step refers to an action configured to run in a container.
  final dynamic container;
  /// Prevents a workflow run from failing when a job fails. Set to true to allow a workflow run to pass when this job fails.
  final dynamic continueOnError;
  /// A map of default settings that will apply to all steps in the job.
  final Defaults? defaults;
  /// A map of environment variables that are available to all steps in the job.
  final dynamic env;
  /// The environment that the job references.
  final dynamic environment;
  /// You can use the if conditional to prevent a job from running unless a condition is met. You can use any supported context and expression to create a conditional.
  /// Expressions in an if conditional do not require the ${{ }} syntax. For more information, see https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions.
  final bool? if_;
  /// The name of the job displayed on GitHub.
  final String? name;
  final dynamic needs;
  /// A map of outputs for a job. Job outputs are available to all downstream jobs that depend on this job.
  final NormalJobOutputs? outputs;
  final dynamic permissions;
  /// The type of machine to run the job on. The machine can be either a GitHub-hosted runner, or a self-hosted runner.
  final dynamic runsOn;
  /// Additional containers to host services for a job in a workflow. These are useful for creating databases or cache services like redis. The runner on the virtual machine will automatically create a network and manage the life cycle of the service containers.
  /// When you use a service container for a job or your step uses container actions, you don't need to set port information to access the service. Docker automatically exposes all ports between containers on the same network.
  /// When both the job and the action run in a container, you can directly reference the container by its hostname. The hostname is automatically mapped to the service name.
  /// When a step does not use a container action, you must access the service using localhost and bind the ports.
  final NormalJobServices? services;
  /// A job contains a sequence of tasks called steps. Steps can run commands, run setup tasks, or run an action in your repository, a public repository, or an action published in a Docker registry. Not all steps run actions, but all actions run as a step. Each step runs in its own process in the virtual environment and has access to the workspace and filesystem. Because steps run in their own process, changes to environment variables are not preserved between steps. GitHub provides built-in steps to set up and complete a job.
  /// Must contain either `uses` or `run`
  final List<Step>? steps;
  /// A strategy creates a build matrix for your jobs. You can define different variations of an environment to run each job in.
  final NormalJobStrategy? strategy;
  /// The maximum number of minutes to let a workflow run before GitHub automatically cancels it. Default: 360
  /// 
  /// Default: 360.
  final dynamic timeoutMinutes;

  const NormalJob({
    this.concurrency,
    this.container,
    this.continueOnError,
    this.defaults,
    this.env,
    this.environment,
    this.if_,
    this.name,
    this.needs,
    this.outputs,
    this.permissions,
    required this.runsOn,
    this.services,
    this.steps,
    this.strategy,
    this.timeoutMinutes,
  }) : super();

  factory NormalJob.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final concurrency = json['concurrency'];
    remaining.remove('concurrency');
    final container = json['container'];
    remaining.remove('container');
    final continueOnError = json['continue-on-error'];
    remaining.remove('continue-on-error');
    final defaults = json['defaults'] == null ? null : Defaults.fromJson((json['defaults'] as Map).cast<String, dynamic>());
    remaining.remove('defaults');
    final env = json['env'];
    remaining.remove('env');
    final environment = json['environment'];
    remaining.remove('environment');
    final if_ = json['if'] as bool?;
    remaining.remove('if');
    final name = json['name'] as String?;
    remaining.remove('name');
    final needs = json['needs'];
    remaining.remove('needs');
    final outputs = json['outputs'] == null ? null : NormalJobOutputs.fromJson((json['outputs'] as Map).cast<String, dynamic>());
    remaining.remove('outputs');
    final permissions = json['permissions'];
    remaining.remove('permissions');
    final runsOn = json['runs-on'];
    remaining.remove('runs-on');
    final services = json['services'] == null ? null : NormalJobServices.fromJson((json['services'] as Map).cast<String, dynamic>());
    remaining.remove('services');
    final steps = json['steps'] == null ? null : (json['steps'] as List).map((e) => Step.fromJson((e as Map).cast<String, dynamic>())).toList();
    remaining.remove('steps');
    final strategy = json['strategy'] == null ? null : NormalJobStrategy.fromJson((json['strategy'] as Map).cast<String, dynamic>());
    remaining.remove('strategy');
    final timeoutMinutes = json['timeout-minutes'];
    remaining.remove('timeout-minutes');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return NormalJob(
      concurrency: concurrency,
      container: container,
      continueOnError: continueOnError,
      defaults: defaults,
      env: env,
      environment: environment,
      if_: if_,
      name: name,
      needs: needs,
      outputs: outputs,
      permissions: permissions,
      runsOn: runsOn,
      services: services,
      steps: steps,
      strategy: strategy,
      timeoutMinutes: timeoutMinutes,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (concurrency != null) map['concurrency'] = concurrency;
    if (container != null) map['container'] = container;
    if (continueOnError != null) map['continue-on-error'] = continueOnError;
    if (defaults != null) map['defaults'] = defaults!.toJson();
    if (env != null) map['env'] = env;
    if (environment != null) map['environment'] = environment;
    if (if_ != null) map['if'] = if_;
    if (name != null) map['name'] = name;
    if (needs != null) map['needs'] = needs;
    if (outputs != null) map['outputs'] = outputs!.toJson();
    if (permissions != null) map['permissions'] = permissions;
    map['runs-on'] = runsOn;
    if (services != null) map['services'] = services!.toJson();
    if (steps != null) map['steps'] = steps!.map((e) => e.toJson()).toList();
    if (strategy != null) map['strategy'] = strategy!.toJson();
    if (timeoutMinutes != null) map['timeout-minutes'] = timeoutMinutes;
    return map;
  }
}
