// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum PermissionsEventActions { read, write, none }

extension PermissionsEventActionsJson on PermissionsEventActions {
  String toJson() => const {
        PermissionsEventActions.read: 'read',
        PermissionsEventActions.write: 'write',
        PermissionsEventActions.none: 'none',
      }[this]!;

  static PermissionsEventActions fromJson(String value) => const {
        'read': PermissionsEventActions.read,
        'write': PermissionsEventActions.write,
        'none': PermissionsEventActions.none,
      }[value]!;
}
