// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'permissions_event_actions.dart';
import 'permissions_event_models.dart';
import 'validation_error.dart';

class PermissionsEvent {
  final PermissionsEventActions? actions;
  final PermissionsEventActions? attestations;
  final PermissionsEventActions? checks;
  final PermissionsEventActions? contents;
  final PermissionsEventActions? deployments;
  final PermissionsEventActions? discussions;
  final PermissionsEventActions? idToken;
  final PermissionsEventActions? issues;
  final PermissionsEventModels? models;
  final PermissionsEventActions? packages;
  final PermissionsEventActions? pages;
  final PermissionsEventActions? pullRequests;
  final PermissionsEventActions? repositoryProjects;
  final PermissionsEventActions? securityEvents;
  final PermissionsEventActions? statuses;

  const PermissionsEvent({
    this.actions,
    this.attestations,
    this.checks,
    this.contents,
    this.deployments,
    this.discussions,
    this.idToken,
    this.issues,
    this.models,
    this.packages,
    this.pages,
    this.pullRequests,
    this.repositoryProjects,
    this.securityEvents,
    this.statuses,
  });

  factory PermissionsEvent.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final actions = json['actions'] == null ? null : PermissionsEventActionsJson.fromJson(json['actions'] as String);
    remaining.remove('actions');
    final attestations = json['attestations'] == null ? null : PermissionsEventActionsJson.fromJson(json['attestations'] as String);
    remaining.remove('attestations');
    final checks = json['checks'] == null ? null : PermissionsEventActionsJson.fromJson(json['checks'] as String);
    remaining.remove('checks');
    final contents = json['contents'] == null ? null : PermissionsEventActionsJson.fromJson(json['contents'] as String);
    remaining.remove('contents');
    final deployments = json['deployments'] == null ? null : PermissionsEventActionsJson.fromJson(json['deployments'] as String);
    remaining.remove('deployments');
    final discussions = json['discussions'] == null ? null : PermissionsEventActionsJson.fromJson(json['discussions'] as String);
    remaining.remove('discussions');
    final idToken = json['id-token'] == null ? null : PermissionsEventActionsJson.fromJson(json['id-token'] as String);
    remaining.remove('id-token');
    final issues = json['issues'] == null ? null : PermissionsEventActionsJson.fromJson(json['issues'] as String);
    remaining.remove('issues');
    final models = json['models'] == null ? null : PermissionsEventModelsJson.fromJson(json['models'] as String);
    remaining.remove('models');
    final packages = json['packages'] == null ? null : PermissionsEventActionsJson.fromJson(json['packages'] as String);
    remaining.remove('packages');
    final pages = json['pages'] == null ? null : PermissionsEventActionsJson.fromJson(json['pages'] as String);
    remaining.remove('pages');
    final pullRequests = json['pull-requests'] == null ? null : PermissionsEventActionsJson.fromJson(json['pull-requests'] as String);
    remaining.remove('pull-requests');
    final repositoryProjects = json['repository-projects'] == null ? null : PermissionsEventActionsJson.fromJson(json['repository-projects'] as String);
    remaining.remove('repository-projects');
    final securityEvents = json['security-events'] == null ? null : PermissionsEventActionsJson.fromJson(json['security-events'] as String);
    remaining.remove('security-events');
    final statuses = json['statuses'] == null ? null : PermissionsEventActionsJson.fromJson(json['statuses'] as String);
    remaining.remove('statuses');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return PermissionsEvent(
      actions: actions,
      attestations: attestations,
      checks: checks,
      contents: contents,
      deployments: deployments,
      discussions: discussions,
      idToken: idToken,
      issues: issues,
      models: models,
      packages: packages,
      pages: pages,
      pullRequests: pullRequests,
      repositoryProjects: repositoryProjects,
      securityEvents: securityEvents,
      statuses: statuses,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (actions != null) map['actions'] = actions!.toJson();
    if (attestations != null) map['attestations'] = attestations!.toJson();
    if (checks != null) map['checks'] = checks!.toJson();
    if (contents != null) map['contents'] = contents!.toJson();
    if (deployments != null) map['deployments'] = deployments!.toJson();
    if (discussions != null) map['discussions'] = discussions!.toJson();
    if (idToken != null) map['id-token'] = idToken!.toJson();
    if (issues != null) map['issues'] = issues!.toJson();
    if (models != null) map['models'] = models!.toJson();
    if (packages != null) map['packages'] = packages!.toJson();
    if (pages != null) map['pages'] = pages!.toJson();
    if (pullRequests != null) map['pull-requests'] = pullRequests!.toJson();
    if (repositoryProjects != null) map['repository-projects'] = repositoryProjects!.toJson();
    if (securityEvents != null) map['security-events'] = securityEvents!.toJson();
    if (statuses != null) map['statuses'] = statuses!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
