// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

part of 'github_workflow_jobs_pattern_property1.dart';

/// Each job must have an id to associate with the job. The key job_id is a string and its value is a map of the job's configuration data. You must replace <job_id> with a string that is unique to the jobs object. The <job_id> must start with a letter or _ and contain only alphanumeric characters, -, or _.
class ReusableWorkflowCallJob extends GithubWorkflowJobsPatternProperty1 {
  /// Concurrency ensures that only a single job or workflow using the same concurrency group will run at a time. A concurrency group can be any string or expression. The expression can use any context except for the secrets context.
  /// You can also specify concurrency at the workflow level.
  /// When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled. To also cancel any currently running job or workflow in the same concurrency group, specify cancel-in-progress: true.
  final dynamic concurrency;
  /// You can use the if conditional to prevent a job from running unless a condition is met. You can use any supported context and expression to create a conditional.
  /// Expressions in an if conditional do not require the ${{ }} syntax. For more information, see https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions.
  final bool? if_;
  /// The name of the job displayed on GitHub.
  final String? name;
  final dynamic needs;
  final dynamic permissions;
  /// When a job is used to call a reusable workflow, you can use 'secrets' to provide a map of secrets that are passed to the called workflow. Any secrets that you pass must match the names defined in the called workflow.
  final dynamic secrets;
  /// A strategy creates a build matrix for your jobs. You can define different variations of an environment to run each job in.
  final ReusableWorkflowCallJobStrategy? strategy;
  /// The location and version of a reusable workflow file to run as a job, of the form './{path/to}/{localfile}.yml' or '{owner}/{repo}/{path}/{filename}@{ref}'. {ref} can be a SHA, a release tag, or a branch name. Using the commit SHA is the safest for stability and security.
  final String uses;
  /// A map of inputs that are passed to the called workflow. Any inputs that you pass must match the input specifications defined in the called workflow. Unlike 'jobs.<job_id>.steps[*].with', the inputs you pass with 'jobs.<job_id>.with' are not be available as environment variables in the called workflow. Instead, you can reference the inputs by using the inputs context.
  final dynamic with_;

  const ReusableWorkflowCallJob({
    this.concurrency,
    this.if_,
    this.name,
    this.needs,
    this.permissions,
    this.secrets,
    this.strategy,
    required this.uses,
    this.with_,
  }) : super();

  factory ReusableWorkflowCallJob.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final concurrency = json['concurrency'];
    remaining.remove('concurrency');
    final if_ = json['if'] as bool?;
    remaining.remove('if');
    final name = json['name'] as String?;
    remaining.remove('name');
    final needs = json['needs'];
    remaining.remove('needs');
    final permissions = json['permissions'];
    remaining.remove('permissions');
    final secrets = json['secrets'];
    remaining.remove('secrets');
    final strategy = json['strategy'] == null ? null : ReusableWorkflowCallJobStrategy.fromJson((json['strategy'] as Map).cast<String, dynamic>());
    remaining.remove('strategy');
    final uses = json['uses'] as String;
    remaining.remove('uses');
    final with_ = json['with'];
    remaining.remove('with');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return ReusableWorkflowCallJob(
      concurrency: concurrency,
      if_: if_,
      name: name,
      needs: needs,
      permissions: permissions,
      secrets: secrets,
      strategy: strategy,
      uses: uses,
      with_: with_,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (concurrency != null) map['concurrency'] = concurrency;
    if (if_ != null) map['if'] = if_;
    if (name != null) map['name'] = name;
    if (needs != null) map['needs'] = needs;
    if (permissions != null) map['permissions'] = permissions;
    if (secrets != null) map['secrets'] = secrets;
    if (strategy != null) map['strategy'] = strategy!.toJson();
    map['uses'] = uses;
    if (with_ != null) map['with'] = with_;
    return map;
  }
}
