// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/anchor_test/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

class Person {
  final int? age;
  final String? email;
  /// The person's first name
  final String firstName;
  /// The person's last name
  final String lastName;

  const Person({
    this.age,
    this.email,
    required this.firstName,
    required this.lastName,
  });

  factory Person.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final age = json['age'] as int?;
    remaining.remove('age');
    final email = json['email'] as String?;
    remaining.remove('email');
    final firstName = json['firstName'] as String;
    remaining.remove('firstName');
    final lastName = json['lastName'] as String;
    remaining.remove('lastName');
    return Person(
      age: age,
      email: email,
      firstName: firstName,
      lastName: lastName,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (age != null) map['age'] = age;
    if (email != null) map['email'] = email;
    map['firstName'] = firstName;
    map['lastName'] = lastName;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'age');
    final _value0 = age;
    if (_value0 != null) {
      context?.markProperty(pointer, 'age');
      if (_value0 < 0) {
        throwValidationError(_ptr0, 'minimum', 'Expected value >= 0 but found ' + _value0.toString() + '.');
      }
    }
    final _ptr1 = appendJsonPointer(pointer, 'email');
    final _value1 = email;
    if (_value1 != null) {
      context?.markProperty(pointer, 'email');
    }
    final _ptr2 = appendJsonPointer(pointer, 'firstName');
    final _value2 = firstName;
    context?.markProperty(pointer, 'firstName');
    final _ptr3 = appendJsonPointer(pointer, 'lastName');
    final _value3 = lastName;
    context?.markProperty(pointer, 'lastName');
  }
}
