// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'class22_workflow_dispatch_inputs.dart';

/// You can now create workflows that are manually triggered with the new workflow_dispatch event. You will then see a 'Run workflow' button on the Actions tab, enabling you to easily trigger a run.
class Class22WorkflowDispatch {
  /// Input parameters allow you to specify data that the action expects to use during runtime. GitHub stores input parameters as environment variables. Input ids with uppercase letters are converted to lowercase during runtime. We recommended using lowercase input ids.
  final Class22WorkflowDispatchInputs? inputs;

  const Class22WorkflowDispatch({this.inputs});

  factory Class22WorkflowDispatch.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final inputs = json['inputs'] == null
        ? null
        : Class22WorkflowDispatchInputs.fromJson(
            (json['inputs'] as Map).cast<String, dynamic>(),
          );
    remaining.remove('inputs');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      throw ArgumentError(
        'Unexpected additional properties: ${unmatched.keys.join(', ')}',
      );
    }
    return Class22WorkflowDispatch(inputs: inputs);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (inputs != null) map['inputs'] = inputs!.toJson();
    return map;
  }
}
