// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

class Class02 {
  const Class02();

  factory Class02.fromJson(Map<String, dynamic> json) {
    return Class02();
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    return map;
  }
}
