// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

class Class22ScheduleItem {
  final String? cron;

  const Class22ScheduleItem({this.cron});

  factory Class22ScheduleItem.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final cron = json['cron'] as String?;
    remaining.remove('cron');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      throw ArgumentError(
        'Unexpected additional properties: ${unmatched.keys.join(', ')}',
      );
    }
    return Class22ScheduleItem(cron: cron);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (cron != null) map['cron'] = cron;
    return map;
  }
}
