// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

/// If the image's container registry requires authentication to pull the image, you can use credentials to set a map of the username and password. The credentials are the same values that you would provide to the `docker login` command.
class ContainerCredentials {
  final String? password;
  final String? username;

  const ContainerCredentials({this.password, this.username});

  factory ContainerCredentials.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final password = json['password'] as String?;
    remaining.remove('password');
    final username = json['username'] as String?;
    remaining.remove('username');
    return ContainerCredentials(password: password, username: username);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (password != null) map['password'] = password;
    if (username != null) map['username'] = username;
    return map;
  }
}
