// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'defaults.dart';
import 'github_workflow_jobs.dart';

class GithubWorkflow {
  /// Concurrency ensures that only a single job or workflow using the same concurrency group will run at a time. A concurrency group can be any string or expression. The expression can use any context except for the secrets context.
  /// You can also specify concurrency at the workflow level.
  /// When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled. To also cancel any currently running job or workflow in the same concurrency group, specify cancel-in-progress: true.
  final dynamic concurrency;

  /// A map of default settings that will apply to all jobs in the workflow.
  final Defaults? defaults;

  /// A map of environment variables that are available to all jobs and steps in the workflow.
  final dynamic env;

  /// A workflow run is made up of one or more jobs. Jobs run in parallel by default. To run jobs sequentially, you can define dependencies on other jobs using the jobs.<job_id>.needs keyword.
  /// Each job runs in a fresh instance of the virtual environment specified by runs-on.
  /// You can run an unlimited number of jobs as long as you are within the workflow usage limits. For more information, see https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#usage-limits.
  final GithubWorkflowJobs jobs;

  /// The name of your workflow. GitHub displays the names of your workflows on your repository's actions page. If you omit this field, GitHub sets the name to the workflow's filename.
  final String? name;

  /// The name of the GitHub event that triggers the workflow. You can provide a single event string, array of events, array of event types, or an event configuration map that schedules a workflow or restricts the execution of a workflow to specific files, tags, or branch changes. For a list of available events, see https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows.
  final dynamic on;
  final dynamic permissions;

  /// The name for workflow runs generated from the workflow. GitHub displays the workflow run name in the list of workflow runs on your repository's 'Actions' tab.
  final String? runName;

  const GithubWorkflow({
    this.concurrency,
    this.defaults,
    this.env,
    required this.jobs,
    this.name,
    required this.on,
    this.permissions,
    this.runName,
  });

  factory GithubWorkflow.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final concurrency = json['concurrency'];
    remaining.remove('concurrency');
    final defaults = json['defaults'] == null
        ? null
        : Defaults.fromJson((json['defaults'] as Map).cast<String, dynamic>());
    remaining.remove('defaults');
    final env = json['env'];
    remaining.remove('env');
    final jobs = GithubWorkflowJobs.fromJson(
      (json['jobs'] as Map).cast<String, dynamic>(),
    );
    remaining.remove('jobs');
    final name = json['name'] as String?;
    remaining.remove('name');
    final on = json['on'];
    remaining.remove('on');
    final permissions = json['permissions'];
    remaining.remove('permissions');
    final runName = json['run-name'] as String?;
    remaining.remove('run-name');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      throw ArgumentError(
        'Unexpected additional properties: ${unmatched.keys.join(', ')}',
      );
    }
    return GithubWorkflow(
      concurrency: concurrency,
      defaults: defaults,
      env: env,
      jobs: jobs,
      name: name,
      on: on,
      permissions: permissions,
      runName: runName,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (concurrency != null) map['concurrency'] = concurrency;
    if (defaults != null) map['defaults'] = defaults!.toJson();
    if (env != null) map['env'] = env;
    map['jobs'] = jobs.toJson();
    if (name != null) map['name'] = name;
    map['on'] = on;
    if (permissions != null) map['permissions'] = permissions;
    if (runName != null) map['run-name'] = runName;
    return map;
  }
}
