// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

import 'github_workflow_jobs_pattern_property1.dart';

/// A workflow run is made up of one or more jobs. Jobs run in parallel by default. To run jobs sequentially, you can define dependencies on other jobs using the jobs.<job_id>.needs keyword.
/// Each job runs in a fresh instance of the virtual environment specified by runs-on.
/// You can run an unlimited number of jobs as long as you are within the workflow usage limits. For more information, see https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#usage-limits.
class GithubWorkflowJobs {
  final Map<String, GithubWorkflowJobsPatternProperty1>? patternProperties;

  const GithubWorkflowJobs({this.patternProperties});

  factory GithubWorkflowJobs.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    var unmatched = Map<String, dynamic>.from(remaining);
    Map<String, GithubWorkflowJobsPatternProperty1>? patternPropertiesValue;
    {
      final patternPropertiesMap =
          <String, GithubWorkflowJobsPatternProperty1>{};
      final unmatchedAfterPattern = <String, dynamic>{};
      for (final entry in unmatched.entries) {
        final key = entry.key;
        final value = entry.value;
        var matched = false;
        if (!matched && RegExp('^[_a-zA-Z][a-zA-Z0-9_-]*\$').hasMatch(key)) {
          patternPropertiesMap[key] =
              GithubWorkflowJobsPatternProperty1.fromJson(
                (value as Map).cast<String, dynamic>(),
              );
          matched = true;
        }
        if (!matched) {
          unmatchedAfterPattern[key] = value;
        }
      }
      patternPropertiesValue = patternPropertiesMap.isEmpty
          ? null
          : patternPropertiesMap;
      unmatched = unmatchedAfterPattern;
    }
    if (unmatched.isNotEmpty) {
      throw ArgumentError(
        'Unexpected additional properties: ${unmatched.keys.join(', ')}',
      );
    }
    return GithubWorkflowJobs(patternProperties: patternPropertiesValue);
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (patternProperties != null) {
      for (final entry in patternProperties!.entries) {
        final key = entry.key;
        final value = entry.value;
        var matched = false;
        if (!matched && RegExp('^[_a-zA-Z][a-zA-Z0-9_-]*\$').hasMatch(key)) {
          map[key] = value.toJson();
          matched = true;
        }
        if (!matched) {
          map[key] = value;
        }
      }
    }
    return map;
  }
}
