// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum Machine { linux, macos, windows }

extension MachineJson on Machine {
  String toJson() => const {
    Machine.linux: 'linux',
    Machine.macos: 'macos',
    Machine.windows: 'windows',
  }[this]!;

  static Machine fromJson(String value) => const {
    'linux': Machine.linux,
    'macos': Machine.macos,
    'windows': Machine.windows,
  }[value]!;
}
