// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

/// A strategy creates a build matrix for your jobs. You can define different variations of an environment to run each job in.
class NormalJobStrategy {
  /// When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true
  ///
  /// Default: true.
  final bool? failFast;
  final dynamic matrix;

  /// The maximum number of jobs that can run simultaneously when using a matrix job strategy. By default, GitHub will maximize the number of jobs run in parallel depending on the available runners on GitHub-hosted virtual machines.
  final double? maxParallel;

  const NormalJobStrategy({
    this.failFast,
    required this.matrix,
    this.maxParallel,
  });

  factory NormalJobStrategy.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final failFast = json['fail-fast'] as bool?;
    remaining.remove('fail-fast');
    final matrix = json['matrix'];
    remaining.remove('matrix');
    final maxParallel = json['max-parallel'] as double?;
    remaining.remove('max-parallel');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      throw ArgumentError(
        'Unexpected additional properties: ${unmatched.keys.join(', ')}',
      );
    }
    return NormalJobStrategy(
      failFast: failFast,
      matrix: matrix,
      maxParallel: maxParallel,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (failFast != null) map['fail-fast'] = failFast;
    map['matrix'] = matrix;
    if (maxParallel != null) map['max-parallel'] = maxParallel;
    return map;
  }
}
