// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

enum PermissionsEventModels { read, none }

extension PermissionsEventModelsJson on PermissionsEventModels {
  String toJson() => const {
    PermissionsEventModels.read: 'read',
    PermissionsEventModels.none: 'none',
  }[this]!;

  static PermissionsEventModels fromJson(String value) => const {
    'read': PermissionsEventModels.read,
    'none': PermissionsEventModels.none,
  }[value]!;
}
