// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_workflow/schema.json
// Generated by json_schema2dart

/// A string representing the type of the input.
enum WorkflowDispatchInputType { string, choice, boolean, number, environment }

extension WorkflowDispatchInputTypeJson on WorkflowDispatchInputType {
  String toJson() => const {
    WorkflowDispatchInputType.string: 'string',
    WorkflowDispatchInputType.choice: 'choice',
    WorkflowDispatchInputType.boolean: 'boolean',
    WorkflowDispatchInputType.number: 'number',
    WorkflowDispatchInputType.environment: 'environment',
  }[this]!;

  static WorkflowDispatchInputType fromJson(String value) => const {
    'string': WorkflowDispatchInputType.string,
    'choice': WorkflowDispatchInputType.choice,
    'boolean': WorkflowDispatchInputType.boolean,
    'number': WorkflowDispatchInputType.number,
    'environment': WorkflowDispatchInputType.environment,
  }[value]!;
}
