// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

/// A string identifier to associate with the output. The value of `<output_id>` is a map of the output's metadata. The `<output_id>` must be a unique identifier within the outputs object. The `<output_id>` must start with a letter or `_` and contain only alphanumeric characters, `-`, or `_`.
class OutputsPatternProperty1 {
  /// A string description of the output parameter.
  final String description;

  const OutputsPatternProperty1({
    required this.description,
  });

  factory OutputsPatternProperty1.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final description = json['description'] as String;
    remaining.remove('description');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return OutputsPatternProperty1(
      description: description,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['description'] = description;
    return map;
  }
}
