// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'root_schema_branding_color.dart';
import 'root_schema_branding_icon.dart';
import 'validation_error.dart';

/// You can use a color and Feather icon to create a badge to personalize and distinguish your action. Badges are shown next to your action name in GitHub Marketplace.
class RootSchemaBranding {
  /// The background color of the badge.
  final RootSchemaBrandingColor? color;
  /// The name of the Feather icon to use.
  final RootSchemaBrandingIcon? icon;

  const RootSchemaBranding({
    this.color,
    this.icon,
  });

  factory RootSchemaBranding.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final color = json['color'] == null ? null : RootSchemaBrandingColorJson.fromJson(json['color'] as String);
    remaining.remove('color');
    final icon = json['icon'] == null ? null : RootSchemaBrandingIconJson.fromJson(json['icon'] as String);
    remaining.remove('icon');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return RootSchemaBranding(
      color: color,
      icon: icon,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (color != null) map['color'] = color!.toJson();
    if (icon != null) map['icon'] = icon!.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
