// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

/// The background color of the badge.
enum RootSchemaBrandingColor { white, black, yellow, blue, green, orange, red, purple, grayDark }

extension RootSchemaBrandingColorJson on RootSchemaBrandingColor {
  String toJson() => const {
        RootSchemaBrandingColor.white: 'white',
        RootSchemaBrandingColor.black: 'black',
        RootSchemaBrandingColor.yellow: 'yellow',
        RootSchemaBrandingColor.blue: 'blue',
        RootSchemaBrandingColor.green: 'green',
        RootSchemaBrandingColor.orange: 'orange',
        RootSchemaBrandingColor.red: 'red',
        RootSchemaBrandingColor.purple: 'purple',
        RootSchemaBrandingColor.grayDark: 'gray-dark',
      }[this]!;

  static RootSchemaBrandingColor fromJson(String value) => const {
        'white': RootSchemaBrandingColor.white,
        'black': RootSchemaBrandingColor.black,
        'yellow': RootSchemaBrandingColor.yellow,
        'blue': RootSchemaBrandingColor.blue,
        'green': RootSchemaBrandingColor.green,
        'orange': RootSchemaBrandingColor.orange,
        'red': RootSchemaBrandingColor.red,
        'purple': RootSchemaBrandingColor.purple,
        'gray-dark': RootSchemaBrandingColor.grayDark,
      }[value]!;
}
