// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'root_schema_branding.dart';
import 'root_schema_inputs.dart';
import 'root_schema_runs.dart';
import 'validation_error.dart';

class RootSchema {
  /// The name of the action's author.
  final String? author;
  /// You can use a color and Feather icon to create a badge to personalize and distinguish your action. Badges are shown next to your action name in GitHub Marketplace.
  final RootSchemaBranding? branding;
  /// A short description of the action.
  final String description;
  /// Input parameters allow you to specify data that the action expects to use during runtime. GitHub stores input parameters as environment variables. Input ids with uppercase letters are converted to lowercase during runtime. We recommended using lowercase input ids.
  final RootSchemaInputs? inputs;
  /// The name of your action. GitHub displays the `name` in the Actions tab to help visually identify actions in each job.
  final String name;
  final dynamic outputs;
  final RootSchemaRuns runs;

  const RootSchema({
    this.author,
    this.branding,
    required this.description,
    this.inputs,
    required this.name,
    this.outputs,
    required this.runs,
  });

  factory RootSchema.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final author = json['author'] as String?;
    remaining.remove('author');
    final branding = json['branding'] == null ? null : RootSchemaBranding.fromJson((json['branding'] as Map).cast<String, dynamic>());
    remaining.remove('branding');
    final description = json['description'] as String;
    remaining.remove('description');
    final inputs = json['inputs'] == null ? null : RootSchemaInputs.fromJson((json['inputs'] as Map).cast<String, dynamic>());
    remaining.remove('inputs');
    final name = json['name'] as String;
    remaining.remove('name');
    final outputs = json['outputs'];
    remaining.remove('outputs');
    final runs = RootSchemaRuns.fromJson((json['runs'] as Map).cast<String, dynamic>());
    remaining.remove('runs');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return RootSchema(
      author: author,
      branding: branding,
      description: description,
      inputs: inputs,
      name: name,
      outputs: outputs,
      runs: runs,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (author != null) map['author'] = author;
    if (branding != null) map['branding'] = branding!.toJson();
    map['description'] = description;
    if (inputs != null) map['inputs'] = inputs!.toJson();
    map['name'] = name;
    if (outputs != null) map['outputs'] = outputs;
    map['runs'] = runs.toJson();
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
