// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// A string identifier to associate with the input. The value of `<input_id>` is a map of the input's metadata. The `<input_id>` must be a unique identifier within the inputs object. The `<input_id>` must start with a letter or `_` and contain only alphanumeric characters, `-`, or `_`.
class RootSchemaInputsPatternProperty1 {
  /// A string representing the default value. The default value is used when an input parameter isn't specified in a workflow file.
  final String? default_;
  /// A string shown to users using the deprecated input.
  final String? deprecationMessage;
  /// A string description of the input parameter.
  final String description;
  /// A boolean to indicate whether the action requires the input parameter. Set to `true` when the parameter is required.
  final bool? required;

  const RootSchemaInputsPatternProperty1({
    this.default_,
    this.deprecationMessage,
    required this.description,
    this.required,
  });

  factory RootSchemaInputsPatternProperty1.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final default_ = json['default'] as String?;
    remaining.remove('default');
    final deprecationMessage = json['deprecationMessage'] as String?;
    remaining.remove('deprecationMessage');
    final description = json['description'] as String;
    remaining.remove('description');
    final required = json['required'] as bool?;
    remaining.remove('required');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return RootSchemaInputsPatternProperty1(
      default_: default_,
      deprecationMessage: deprecationMessage,
      description: description,
      required: required,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (default_ != null) map['default'] = default_;
    if (deprecationMessage != null) map['deprecationMessage'] = deprecationMessage;
    map['description'] = description;
    if (required != null) map['required'] = required;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
