// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'runs_composite_steps_item_with.dart';

class RunsCompositeStepsItem {
  /// Prevents a job from failing when a step fails. Set to true to allow a job to pass when this step fails.
  /// 
  /// Default: false.
  final dynamic continueOnError;
  /// Sets a map of environment variables for only that step.
  final dynamic env;
  /// A unique identifier for the step. You can use the `id` to reference the step in contexts.
  final String? id;
  /// You can use the if conditional to prevent a step from running unless a condition is met. You can use any supported context and expression to create a conditional.
  /// Expressions in an if conditional do not require the ${{ }} syntax. For more information, see https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions.
  final String? if_;
  /// The name of the composite run step.
  final String? name;
  /// The command you want to run. This can be inline or a script in your action repository.
  final String? run;
  /// The shell where you want to run the command.
  final dynamic shell;
  /// Selects an action to run as part of a step in your job.
  final String? uses;
  /// A map of the input parameters defined by the action. Each input parameter is a key/value pair. Input parameters are set as environment variables. The variable is prefixed with INPUT_ and converted to upper case.
  final RunsCompositeStepsItemWith? with_;
  /// Specifies the working directory where the command is run.
  final String? workingDirectory;

  const RunsCompositeStepsItem({
    this.continueOnError,
    this.env,
    this.id,
    this.if_,
    this.name,
    this.run,
    this.shell,
    this.uses,
    this.with_,
    this.workingDirectory,
  });

  factory RunsCompositeStepsItem.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final continueOnError = json['continue-on-error'];
    remaining.remove('continue-on-error');
    final env = json['env'];
    remaining.remove('env');
    final id = json['id'] as String?;
    remaining.remove('id');
    final if_ = json['if'] as String?;
    remaining.remove('if');
    final name = json['name'] as String?;
    remaining.remove('name');
    final run = json['run'] as String?;
    remaining.remove('run');
    final shell = json['shell'];
    remaining.remove('shell');
    final uses = json['uses'] as String?;
    remaining.remove('uses');
    final with_ = json['with'] == null ? null : RunsCompositeStepsItemWith.fromJson((json['with'] as Map).cast<String, dynamic>());
    remaining.remove('with');
    final workingDirectory = json['working-directory'] as String?;
    remaining.remove('working-directory');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return RunsCompositeStepsItem(
      continueOnError: continueOnError,
      env: env,
      id: id,
      if_: if_,
      name: name,
      run: run,
      shell: shell,
      uses: uses,
      with_: with_,
      workingDirectory: workingDirectory,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (continueOnError != null) map['continue-on-error'] = continueOnError;
    if (env != null) map['env'] = env;
    if (id != null) map['id'] = id;
    if (if_ != null) map['if'] = if_;
    if (name != null) map['name'] = name;
    if (run != null) map['run'] = run;
    if (shell != null) map['shell'] = shell;
    if (uses != null) map['uses'] = uses;
    if (with_ != null) map['with'] = with_!.toJson();
    if (workingDirectory != null) map['working-directory'] = workingDirectory;
    return map;
  }
}
