// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'runs_composite_step_with.dart';
import 'validation_error.dart';

class RunsCompositeStep {
  /// Prevents a job from failing when a step fails. Set to true to allow a job to pass when this step fails.
  /// 
  /// Default: false.
  final dynamic continueOnError;
  /// Sets a map of environment variables for only that step.
  final dynamic env;
  /// A unique identifier for the step. You can use the `id` to reference the step in contexts.
  final String? id;
  /// You can use the if conditional to prevent a step from running unless a condition is met. You can use any supported context and expression to create a conditional.
  /// Expressions in an if conditional do not require the ${{ }} syntax. For more information, see https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions.
  final String? if_;
  /// The name of the composite run step.
  final String? name;
  /// The command you want to run. This can be inline or a script in your action repository.
  final String? run;
  /// The shell where you want to run the command.
  final dynamic shell;
  /// Selects an action to run as part of a step in your job.
  final String? uses;
  /// A map of the input parameters defined by the action. Each input parameter is a key/value pair. Input parameters are set as environment variables. The variable is prefixed with INPUT_ and converted to upper case.
  final RunsCompositeStepWith? with_;
  /// Specifies the working directory where the command is run.
  final String? workingDirectory;

  const RunsCompositeStep({
    this.continueOnError = false,
    this.env,
    this.id,
    this.if_,
    this.name,
    this.run,
    this.shell,
    this.uses,
    this.with_,
    this.workingDirectory,
  });

  factory RunsCompositeStep.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final continueOnError = (json['continue-on-error']) ?? false;
    remaining.remove('continue-on-error');
    final env = json['env'];
    remaining.remove('env');
    final id = json['id'] as String?;
    remaining.remove('id');
    final if_ = json['if'] as String?;
    remaining.remove('if');
    final name = json['name'] as String?;
    remaining.remove('name');
    final run = json['run'] as String?;
    remaining.remove('run');
    final shell = json['shell'];
    remaining.remove('shell');
    final uses = json['uses'] as String?;
    remaining.remove('uses');
    final with_ = json['with'] == null ? null : RunsCompositeStepWith.fromJson((json['with'] as Map).cast<String, dynamic>());
    remaining.remove('with');
    final workingDirectory = json['working-directory'] as String?;
    remaining.remove('working-directory');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return RunsCompositeStep(
      continueOnError: continueOnError,
      env: env,
      id: id,
      if_: if_,
      name: name,
      run: run,
      shell: shell,
      uses: uses,
      with_: with_,
      workingDirectory: workingDirectory,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (continueOnError != null) map['continue-on-error'] = continueOnError;
    if (env != null) map['env'] = env;
    if (id != null) map['id'] = id;
    if (if_ != null) map['if'] = if_;
    if (name != null) map['name'] = name;
    if (run != null) map['run'] = run;
    if (shell != null) map['shell'] = shell;
    if (uses != null) map['uses'] = uses;
    if (with_ != null) map['with'] = with_!.toJson();
    if (workingDirectory != null) map['working-directory'] = workingDirectory;
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'continue-on-error');
    final _value0 = continueOnError;
    context?.annotate(_ptr0, 'default', false, schemaPointer: '#/definitions/runs-composite/properties/steps/items/properties/continue-on-error');
    if (_value0 != null) {
      context?.markProperty(pointer, 'continue-on-error');
    }
    final _ptr1 = appendJsonPointer(pointer, 'env');
    final _value1 = env;
    if (_value1 != null) {
      context?.markProperty(pointer, 'env');
    }
    final _ptr2 = appendJsonPointer(pointer, 'id');
    final _value2 = id;
    if (_value2 != null) {
      context?.markProperty(pointer, 'id');
    }
    final _ptr3 = appendJsonPointer(pointer, 'if');
    final _value3 = if_;
    if (_value3 != null) {
      context?.markProperty(pointer, 'if');
    }
    final _ptr4 = appendJsonPointer(pointer, 'name');
    final _value4 = name;
    if (_value4 != null) {
      context?.markProperty(pointer, 'name');
    }
    final _ptr5 = appendJsonPointer(pointer, 'run');
    final _value5 = run;
    if (_value5 != null) {
      context?.markProperty(pointer, 'run');
    }
    final _ptr6 = appendJsonPointer(pointer, 'shell');
    final _value6 = shell;
    if (_value6 != null) {
      context?.markProperty(pointer, 'shell');
    }
    final _ptr7 = appendJsonPointer(pointer, 'uses');
    final _value7 = uses;
    if (_value7 != null) {
      context?.markProperty(pointer, 'uses');
    }
    final _ptr8 = appendJsonPointer(pointer, 'with');
    final _value8 = with_;
    if (_value8 != null) {
      context?.markProperty(pointer, 'with');
    }
    final _ptr9 = appendJsonPointer(pointer, 'working-directory');
    final _value9 = workingDirectory;
    if (_value9 != null) {
      context?.markProperty(pointer, 'working-directory');
    }
     final _constraint0Match0 = run != null && shell != null;
     final _constraint0Match1 = uses != null;
     final _constraint0Matches = <bool>[_constraint0Match0, _constraint0Match1];
     final _constraint0MatchCount = _constraint0Matches.where((value) => value).length;
     if (_constraint0MatchCount != 1) {
       throwValidationError(pointer, 'oneOf', 'Expected exactly one of the combinations defined at #/definitions/runs-composite/properties/steps/items/oneOf to be satisfied (["run", "shell"], ["uses"]).');
     }
  }
}
