// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

part of 'root_schema_runs.dart';

/// Configures the path to the composite action, and the application used to execute the code.
class RunsComposite extends RootSchemaRuns {
  /// The run steps that you plan to run in this action.
  final List<RunsCompositeStep> steps;
  /// To use a composite run steps action, set this to 'composite'.
  final String using;

  const RunsComposite({
    required this.steps,
    required this.using,
  }) : super();

  factory RunsComposite.fromJson(Map<String, dynamic> json) {
    final remaining = Map<String, dynamic>.from(json);
    final steps = (json['steps'] as List).map((e) => RunsCompositeStep.fromJson((e as Map).cast<String, dynamic>())).toList();
    remaining.remove('steps');
    final using = json['using'] as String;
    remaining.remove('using');
    var unmatched = Map<String, dynamic>.from(remaining);
    if (unmatched.isNotEmpty) {
      final unexpected = unmatched.keys.join(', ');
      throw ArgumentError('Unexpected additional properties: $unexpected');
    }
    return RunsComposite(
      steps: steps,
      using: using,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['steps'] = steps.map((e) => e.toJson()).toList();
    map['using'] = using;
    return map;
  }

  @override
  void validate({String pointer = '', ValidationContext? context}) {
    final _ptr0 = appendJsonPointer(pointer, 'steps');
    final _value0 = steps;
    context?.markProperty(pointer, 'steps');
    final _lenp0 = _value0.length;
    final _evaluatedp0 = List<bool>.filled(_lenp0, false);
    for (var i = 0; i < _lenp0; i++) {
      final itemPointer = appendJsonPointer(_ptr0, i.toString());
      final item = _value0[i];
      item.validate(pointer: itemPointer, context: context);
      _evaluatedp0[i] = true;
      context?.markItem(_ptr0, i);
    }
    final _ptr1 = appendJsonPointer(pointer, 'using');
    final _value1 = using;
    context?.markProperty(pointer, 'using');
    final _actualp1 = _value1;
    if (_actualp1 != 'composite') {
      throwValidationError(_ptr1, 'const', 'Expected value equal to \'composite\' but found ' + _actualp1.toString() + '.');
    }
  }
}
