// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: example/schemas/github_action/schema.json
// Generated by json_schema2dart

import 'validation_error.dart';

/// A map of the input parameters defined by the action. Each input parameter is a key/value pair. Input parameters are set as environment variables. The variable is prefixed with INPUT_ and converted to upper case.
class RunsCompositeStepWith {

  const RunsCompositeStepWith();

  factory RunsCompositeStepWith.fromJson(Map<String, dynamic> json) {
    return RunsCompositeStepWith(
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    return map;
  }

  void validate({String pointer = '', ValidationContext? context}) {}
}
